import type { LanguageCode } from "@/lib/languages";

export type CreateQuizCopy = {
  backHome: string;
  title: string;
  intro: string;
  quizLanguage: string;
  authorLabel: string;
  authorPlaceholder: string;
  anonymousAuthor: string;
  imageTitle: string;
  imageHint: string;
  pickImage: string;
  zoom: string;
  originalPreviewAlt: string;
  originalReveal: string;
  optionsTitle: string;
  optionsHint: string;
  aiButton: string;
  aiPending: string;
  optionN: string;
  optionCorrect: string;
  optionText: string;
  tauntLabel: string;
  publish: string;
  compressing: string;
  moderating: string;
  uploading: string;
  saving: string;
  signedIn: string;
  signOut: string;
  signInHint: string;
  password: string;
  signUp: string;
  published: string;
  viewScore: string;
  sizeLine: string;
  cropAlt: string;
  originalAlt: string;
  cropCaption: string;
  originalCaption: string;
  another: string;
  scoreTitle: string;
  close: string;
  blindSolve: string;
  visualRich: string;
  distractorQuality: string;
  community: string;
  passed: string;
  failedCheck: string;
  noVisual: string;
  noDistractor: string;
  aiSuggestion: string;
  excellent: string;
  acceptable: string;
  needAnswer: string;
  needCrop: string;
  cropTooSmall: string;
  aiFailed: string;
  notImage: string;
  passwordShort: string;
  signedUp: string;
  authorLength: string;
  needImage: string;
  cropPending: string;
  optionLength: string;
  tauntLength: string;
  needCorrect: string;
  needLogin: string;
  cropCompressFail: string;
  reviewFail: string;
  originalCompressFail: string;
  publishFail: string;
  badCredentials: string;
  emailUnconfirmed: string;
  noPermission: string;
  tooLarge: string;
  webpOnly: string;
  moderationTitle: string;
  safetyZero: string;
  scoreLow: string;
  adjustHint: string;
  blindResult: string;
  blindTest: string;
  visualShort: string;
  deception: string;
  safetyShort: string;
  improve: string;
  backAdjust: string;
  guidelines: string;
};

const FULL_COPY = {
  "zh-TW": {
    backHome: "返回首頁",
    title: "出一題局部猜謎",
    intro: "上傳一張圖，框出玩家看得見的特寫。原圖與特寫都會在瀏覽器轉成 150KB 以內的 WebP 再上傳。",
    quizLanguage: "出題語言：",
    authorLabel: "作者名稱",
    authorPlaceholder: "顯示在題目上的名字",
    anonymousAuthor: "匿名出題者",
    imageTitle: "圖片與特寫",
    imageHint: "拖拽或滾輪拉近，白框裡的範圍就是玩家要猜的局部。",
    pickImage: "選擇圖片",
    zoom: "拉近",
    originalPreviewAlt: "原圖預覽",
    originalReveal: "原圖，答對後揭曉",
    optionsTitle: "四個選項",
    optionsHint: "標一個正解。每個選項都要有專屬毒舌評語，玩家選錯才會看到。",
    aiButton: "🤖 AI 一鍵生成選項與毒舌評語",
    aiPending: "AI 思考中...",
    optionN: "選項 {n}",
    optionCorrect: "選項 {n} · 正解",
    optionText: "選項文字",
    tauntLabel: "專屬毒舌評語",
    publish: "發布題目",
    compressing: "壓縮成 WebP…",
    moderating: "綜合審題…",
    uploading: "上傳圖片…",
    saving: "寫入題目…",
    signedIn: "已登入",
    signOut: "登出",
    signInHint: "登入後才能發布。題目會記在你的帳號下。",
    password: "密碼",
    signUp: "註冊",
    published: "題目已發布",
    viewScore: "查看評分明細",
    sizeLine: "特寫 {crop}，原圖 {original}",
    cropAlt: "已上傳的特寫",
    originalAlt: "已上傳的原圖",
    cropCaption: "玩家看到的特寫",
    originalCaption: "答對後揭曉的原圖",
    another: "再出一題",
    scoreTitle: "評分明細",
    close: "關閉",
    blindSolve: "盲猜可解性",
    visualRich: "視覺特徵度",
    distractorQuality: "干擾項品質",
    community: "社群合規",
    passed: "通過",
    failedCheck: "未通過",
    noVisual: "尚未留下特徵清晰度評估。",
    noDistractor: "尚未留下干擾項評估。",
    aiSuggestion: "AI 建議",
    excellent: "優質",
    acceptable: "合格",
    needAnswer: "請先輸入正解名稱",
    needCrop: "請先上傳圖片並框出特寫",
    cropTooSmall: "特寫區域太小，請把框拉大一點",
    aiFailed: "生成失敗，請再試一次",
    notImage: "請上傳圖片檔",
    passwordShort: "密碼至少 6 個字元",
    signedUp: "註冊成功。請到信箱完成驗證，再回來登入。",
    authorLength: "作者名稱需要 1 到 40 個字",
    needImage: "請先上傳圖片",
    cropPending: "請等特寫裁切區域準備好",
    optionLength: "選項 {n} 的文字需要 1 到 120 個字",
    tauntLength: "選項 {n} 的毒舌評語需要 1 到 280 個字",
    needCorrect: "請標出一個正解",
    needLogin: "請先登入再出題",
    cropCompressFail: "特寫壓不到 150KB 以內，請把裁切範圍縮小再試",
    reviewFail: "預審失敗，請再試一次",
    originalCompressFail: "原圖壓不到 150KB 以內，請換一張再試",
    publishFail: "出題失敗，請再試一次",
    badCredentials: "帳號或密碼不正確",
    emailUnconfirmed: "請先到信箱完成驗證，再登入",
    noPermission: "沒有寫入權限。請確認已登入。",
    tooLarge: "圖片超過 150KB，已中止上傳",
    webpOnly: "只能上傳 WebP",
    moderationTitle: "這題還沒通過預審",
    safetyZero: "安全合規未通過，總分已歸零。題目尚未發布。",
    scoreLow: "綜合分數 {score}/100，未達 60 分。題目尚未發布。",
    adjustHint: "請依盲猜結果重新調整裁切，或修改正解與干擾項後再發布。",
    blindResult: "AI 盲猜結果",
    blindTest: "盲猜測驗",
    visualShort: "視覺特徵",
    deception: "干擾項欺騙性",
    safetyShort: "安全合規",
    improve: "改善建議",
    backAdjust: "回去調整",
    guidelines: "查看完整審核標準",
  },
  "zh-CN": {
    backHome: "返回首页",
    title: "出一题局部猜谜",
    intro: "上传一张图，框出玩家看得见的特写。原图与特写都会在浏览器转成 150KB 以内的 WebP 再上传。",
    quizLanguage: "出题语言：",
    authorLabel: "作者名称",
    authorPlaceholder: "显示在题目上的名字",
    anonymousAuthor: "匿名出题者",
    imageTitle: "图片与特写",
    imageHint: "拖拽或滚轮拉近，白框里的范围就是玩家要猜的局部。",
    pickImage: "选择图片",
    zoom: "拉近",
    originalPreviewAlt: "原图预览",
    originalReveal: "原图，答对后揭晓",
    optionsTitle: "四个选项",
    optionsHint: "标一个正解。每个选项都要有专属毒舌评语，玩家选错才会看到。",
    aiButton: "🤖 AI 一键生成选项与毒舌评语",
    aiPending: "AI 思考中...",
    optionN: "选项 {n}",
    optionCorrect: "选项 {n} · 正解",
    optionText: "选项文字",
    tauntLabel: "专属毒舌评语",
    publish: "发布题目",
    compressing: "压缩成 WebP…",
    moderating: "综合审题…",
    uploading: "上传图片…",
    saving: "写入题目…",
    signedIn: "已登录",
    signOut: "登出",
    signInHint: "登录后才能发布。题目会记在你的账号下。",
    password: "密码",
    signUp: "注册",
    published: "题目已发布",
    viewScore: "查看评分明细",
    sizeLine: "特写 {crop}，原图 {original}",
    cropAlt: "已上传的特写",
    originalAlt: "已上传的原图",
    cropCaption: "玩家看到的特写",
    originalCaption: "答对后揭晓的原图",
    another: "再出一题",
    scoreTitle: "评分明细",
    close: "关闭",
    blindSolve: "盲猜可解性",
    visualRich: "视觉特征度",
    distractorQuality: "干扰项品质",
    community: "社群合规",
    passed: "通过",
    failedCheck: "未通过",
    noVisual: "尚未留下特征清晰度评估。",
    noDistractor: "尚未留下干扰项评估。",
    aiSuggestion: "AI 建议",
    excellent: "优质",
    acceptable: "合格",
    needAnswer: "请先输入正解名称",
    needCrop: "请先上传图片并框出特写",
    cropTooSmall: "特写区域太小，请把框拉大一点",
    aiFailed: "生成失败，请再试一次",
    notImage: "请上传图片文件",
    passwordShort: "密码至少 6 个字符",
    signedUp: "注册成功。请到邮箱完成验证，再回来登录。",
    authorLength: "作者名称需要 1 到 40 个字",
    needImage: "请先上传图片",
    cropPending: "请等特写裁切区域准备好",
    optionLength: "选项 {n} 的文字需要 1 到 120 个字",
    tauntLength: "选项 {n} 的毒舌评语需要 1 到 280 个字",
    needCorrect: "请标出一个正解",
    needLogin: "请先登录再出题",
    cropCompressFail: "特写压不到 150KB 以内，请把裁切范围缩小再试",
    reviewFail: "预审失败，请再试一次",
    originalCompressFail: "原图压不到 150KB 以内，请换一张再试",
    publishFail: "出题失败，请再试一次",
    badCredentials: "账号或密码不正确",
    emailUnconfirmed: "请先到邮箱完成验证，再登录",
    noPermission: "没有写入权限。请确认已登录。",
    tooLarge: "图片超过 150KB，已中止上传",
    webpOnly: "只能上传 WebP",
    moderationTitle: "这题还没通过预审",
    safetyZero: "安全合规未通过，总分已归零。题目尚未发布。",
    scoreLow: "综合分数 {score}/100，未达 60 分。题目尚未发布。",
    adjustHint: "请依盲猜结果重新调整裁切，或修改正解与干扰项后再发布。",
    blindResult: "AI 盲猜结果",
    blindTest: "盲猜测验",
    visualShort: "视觉特征",
    deception: "干扰项欺骗性",
    safetyShort: "安全合规",
    improve: "改善建议",
    backAdjust: "回去调整",
    guidelines: "查看完整审核标准",
  },
  en: {
    backHome: "Back to Home",
    title: "Make a close-up quiz",
    intro: "Upload a photo and frame the close-up players will see. Both images are converted to WebP under 150KB in the browser before upload.",
    quizLanguage: "Quiz language:",
    authorLabel: "Author name",
    authorPlaceholder: "Name shown on the quiz",
    anonymousAuthor: "Anonymous",
    imageTitle: "Image and close-up",
    imageHint: "Drag or scroll to zoom. The white frame is the close-up players must guess.",
    pickImage: "Choose image",
    zoom: "Zoom",
    originalPreviewAlt: "Original preview",
    originalReveal: "Original, revealed after a correct guess",
    optionsTitle: "Four options",
    optionsHint: "Mark one correct answer. Every option needs its own Savage Roast, shown only when a player picks the wrong one.",
    aiButton: "🤖 Generate options and Savage Roasts",
    aiPending: "AI is thinking...",
    optionN: "Option {n}",
    optionCorrect: "Option {n} · Answer",
    optionText: "Option text",
    tauntLabel: "Savage Roast",
    publish: "Publish quiz",
    compressing: "Converting to WebP…",
    moderating: "Reviewing…",
    uploading: "Uploading…",
    saving: "Saving quiz…",
    signedIn: "Signed in",
    signOut: "Sign out",
    signInHint: "Sign in to publish. The quiz is saved to your account.",
    password: "Password",
    signUp: "Sign up",
    published: "Quiz published",
    viewScore: "View score details",
    sizeLine: "Close-up {crop}, original {original}",
    cropAlt: "Uploaded close-up",
    originalAlt: "Uploaded original",
    cropCaption: "Close-up players see",
    originalCaption: "Original revealed after a correct guess",
    another: "Make another",
    scoreTitle: "Score details",
    close: "Close",
    blindSolve: "Blind solvability",
    visualRich: "Visual detail",
    distractorQuality: "Distractor quality",
    community: "Community safety",
    passed: "Passed",
    failedCheck: "Failed",
    noVisual: "No visual-detail note yet.",
    noDistractor: "No distractor note yet.",
    aiSuggestion: "AI suggestion",
    excellent: "Excellent",
    acceptable: "OK",
    needAnswer: "Enter the correct answer first",
    needCrop: "Upload an image and frame the close-up first",
    cropTooSmall: "The close-up is too small. Make the frame larger.",
    aiFailed: "Generation failed. Try again.",
    notImage: "Please upload an image file",
    passwordShort: "Password must be at least 6 characters",
    signedUp: "Account created. Confirm the email, then sign in.",
    authorLength: "Author name must be 1 to 40 characters",
    needImage: "Upload an image first",
    cropPending: "Wait until the crop area is ready",
    optionLength: "Option {n} text must be 1 to 120 characters",
    tauntLength: "Option {n} Savage Roast must be 1 to 280 characters",
    needCorrect: "Mark one correct answer",
    needLogin: "Sign in before publishing",
    cropCompressFail: "The close-up could not fit under 150KB. Crop a smaller area.",
    reviewFail: "Review failed. Try again.",
    originalCompressFail: "The original could not fit under 150KB. Try another image.",
    publishFail: "Could not publish. Try again.",
    badCredentials: "Incorrect email or password",
    emailUnconfirmed: "Confirm your email, then sign in",
    noPermission: "No write permission. Make sure you are signed in.",
    tooLarge: "Image is over 150KB. Upload stopped.",
    webpOnly: "Only WebP can be uploaded",
    moderationTitle: "This quiz did not pass review",
    safetyZero: "Safety check failed and the score is zero. Nothing was published.",
    scoreLow: "Score {score}/100, below 60. Nothing was published.",
    adjustHint: "Adjust the crop from the blind guesses, or edit the answer and distractors, then publish again.",
    blindResult: "AI blind guesses",
    blindTest: "Blind test",
    visualShort: "Visual cues",
    deception: "Distractor trickiness",
    safetyShort: "Safety",
    improve: "How to improve",
    backAdjust: "Go back and edit",
    guidelines: "View the full review rules",
  },
  es: {
    backHome: "Volver al inicio",
    title: "Crear un acertijo de detalle",
    intro: "Sube una foto y encuadra el detalle que verán los jugadores. Ambas imágenes se convierten a WebP de menos de 150KB en el navegador antes de subirse.",
    quizLanguage: "Idioma de la pregunta:",
    authorLabel: "Nombre del autor",
    authorPlaceholder: "Nombre que se muestra en la pregunta",
    anonymousAuthor: "Anónimo",
    imageTitle: "Imagen y detalle",
    imageHint: "Arrastra o usa la rueda para acercar. El marco blanco es el detalle que hay que adivinar.",
    pickImage: "Elegir imagen",
    zoom: "Zoom",
    originalPreviewAlt: "Vista de la original",
    originalReveal: "Original, se revela al acertar",
    optionsTitle: "Cuatro opciones",
    optionsHint: "Marca una respuesta correcta. Cada opción necesita su Comentario Mordaz, visible solo si se elige mal.",
    aiButton: "🤖 Generar opciones y comentarios mordaces",
    aiPending: "La IA está pensando...",
    optionN: "Opción {n}",
    optionCorrect: "Opción {n} · Correcta",
    optionText: "Texto de la opción",
    tauntLabel: "Comentario Mordaz",
    publish: "Publicar",
    compressing: "Convirtiendo a WebP…",
    moderating: "Revisando…",
    uploading: "Subiendo…",
    saving: "Guardando…",
    signedIn: "Sesión iniciada",
    signOut: "Salir",
    signInHint: "Entra para publicar. La pregunta queda en tu cuenta.",
    password: "Contraseña",
    signUp: "Registrarse",
    published: "Pregunta publicada",
    viewScore: "Ver el detalle de la nota",
    sizeLine: "Detalle {crop}, original {original}",
    cropAlt: "Detalle subido",
    originalAlt: "Original subida",
    cropCaption: "Detalle que ven los jugadores",
    originalCaption: "Original que se revela al acertar",
    another: "Crear otra",
    scoreTitle: "Detalle de la nota",
    close: "Cerrar",
    blindSolve: "Se puede adivinar a ciegas",
    visualRich: "Detalle visual",
    distractorQuality: "Calidad de distractores",
    community: "Seguridad",
    passed: "Aprobado",
    failedCheck: "No aprobado",
    noVisual: "Aún no hay nota visual.",
    noDistractor: "Aún no hay nota de distractores.",
    aiSuggestion: "Sugerencia de la IA",
    excellent: "Excelente",
    acceptable: "Aceptable",
    needAnswer: "Escribe primero la respuesta correcta",
    needCrop: "Sube una imagen y encuadra el detalle",
    cropTooSmall: "El detalle es demasiado pequeño. Agranda el marco.",
    aiFailed: "No se pudo generar. Inténtalo de nuevo.",
    notImage: "Sube un archivo de imagen",
    passwordShort: "La contraseña debe tener al menos 6 caracteres",
    signedUp: "Cuenta creada. Confirma el correo y luego entra.",
    authorLength: "El nombre debe tener de 1 a 40 caracteres",
    needImage: "Sube una imagen primero",
    cropPending: "Espera a que el recorte esté listo",
    optionLength: "El texto de la opción {n} debe tener de 1 a 120 caracteres",
    tauntLength: "El Comentario Mordaz de la opción {n} debe tener de 1 a 280 caracteres",
    needCorrect: "Marca una respuesta correcta",
    needLogin: "Entra antes de publicar",
    cropCompressFail: "El detalle no cabe en 150KB. Recorta un área menor.",
    reviewFail: "La revisión falló. Inténtalo de nuevo.",
    originalCompressFail: "La original no cabe en 150KB. Prueba otra imagen.",
    publishFail: "No se pudo publicar. Inténtalo de nuevo.",
    badCredentials: "Correo o contraseña incorrectos",
    emailUnconfirmed: "Confirma el correo y luego entra",
    noPermission: "Sin permiso de escritura. Confirma que has entrado.",
    tooLarge: "La imagen supera 150KB. Se detuvo la subida.",
    webpOnly: "Solo se puede subir WebP",
    moderationTitle: "Esta pregunta no pasó la revisión",
    safetyZero: "No pasó la seguridad y la nota es cero. No se publicó.",
    scoreLow: "Nota {score}/100, por debajo de 60. No se publicó.",
    adjustHint: "Ajusta el recorte según las adivinanzas, o edita la respuesta y los distractores, y publica de nuevo.",
    blindResult: "Adivinanzas de la IA",
    blindTest: "Prueba a ciegas",
    visualShort: "Pistas visuales",
    deception: "Engaño de los distractores",
    safetyShort: "Seguridad",
    improve: "Cómo mejorarla",
    backAdjust: "Volver a editar",
    guidelines: "Ver las reglas completas",
  },
  ja: {
    backHome: "ホームへ戻る",
    title: "部分クイズを作る",
    intro: "画像を上げて、プレイヤーが見るアップを枠で囲みます。原画もアップも、ブラウザで150KB以内のWebPにしてからアップロードします。",
    quizLanguage: "出題言語：",
    authorLabel: "作者名",
    authorPlaceholder: "問題に表示する名前",
    anonymousAuthor: "匿名",
    imageTitle: "画像とアップ",
    imageHint: "ドラッグするかホイールで拡大。白枠の中がプレイヤーの見る部分です。",
    pickImage: "画像を選ぶ",
    zoom: "拡大",
    originalPreviewAlt: "原画プレビュー",
    originalReveal: "原画。正解後に公開",
    optionsTitle: "4つの選択肢",
    optionsHint: "正解を1つ選んでください。各選択肢に辛口コメントが必要で、間違えた人だけが見ます。",
    aiButton: "🤖 AIで選択肢と辛口コメントを作る",
    aiPending: "AIが考えています...",
    optionN: "選択肢 {n}",
    optionCorrect: "選択肢 {n} · 正解",
    optionText: "選択肢の文字",
    tauntLabel: "辛口コメント",
    publish: "問題を公開",
    compressing: "WebPに変換中…",
    moderating: "審査中…",
    uploading: "アップロード中…",
    saving: "保存中…",
    signedIn: "ログイン中",
    signOut: "ログアウト",
    signInHint: "公開にはログインが必要です。問題はあなたのアカウントに残ります。",
    password: "パスワード",
    signUp: "登録",
    published: "公開しました",
    viewScore: "採点の詳細",
    sizeLine: "アップ {crop}、原画 {original}",
    cropAlt: "アップロードしたアップ",
    originalAlt: "アップロードした原画",
    cropCaption: "プレイヤーが見るアップ",
    originalCaption: "正解後に公開される原画",
    another: "もう1問作る",
    scoreTitle: "採点の詳細",
    close: "閉じる",
    blindSolve: "見ただけで解けるか",
    visualRich: "見た目の特徴",
    distractorQuality: "誤答の質",
    community: "安全",
    passed: "合格",
    failedCheck: "不合格",
    noVisual: "特徴の評価はまだありません。",
    noDistractor: "誤答の評価はまだありません。",
    aiSuggestion: "AIの提案",
    excellent: "優秀",
    acceptable: "合格",
    needAnswer: "先に正解の名前を入力してください",
    needCrop: "先に画像を上げてアップを枠で囲んでください",
    cropTooSmall: "アップが小さすぎます。枠を大きくしてください。",
    aiFailed: "生成に失敗しました。もう一度試してください。",
    notImage: "画像ファイルを選んでください",
    passwordShort: "パスワードは6文字以上です",
    signedUp: "登録しました。メールを確認してからログインしてください。",
    authorLength: "作者名は1〜40文字です",
    needImage: "先に画像を上げてください",
    cropPending: "切り抜きの準備を待ってください",
    optionLength: "選択肢 {n} の文字は1〜120文字です",
    tauntLength: "選択肢 {n} の辛口コメントは1〜280文字です",
    needCorrect: "正解を1つ選んでください",
    needLogin: "公開する前にログインしてください",
    cropCompressFail: "アップを150KB以内にできません。範囲を小さくしてください。",
    reviewFail: "審査に失敗しました。もう一度試してください。",
    originalCompressFail: "原画を150KB以内にできません。別の画像を試してください。",
    publishFail: "公開できませんでした。もう一度試してください。",
    badCredentials: "メールかパスワードが違います",
    emailUnconfirmed: "メールを確認してからログインしてください",
    noPermission: "書き込み権限がありません。ログインを確認してください。",
    tooLarge: "画像が150KBを超えたため、アップロードを中止しました",
    webpOnly: "アップロードできるのはWebPだけです",
    moderationTitle: "この問題は事前審査を通りませんでした",
    safetyZero: "安全審査に落ち、点数は0です。公開されていません。",
    scoreLow: "総合 {score}/100 で60点未満です。公開されていません。",
    adjustHint: "盲猜の結果を見て枠を直すか、正解と誤答を変えてから再度公開してください。",
    blindResult: "AIの盲猜",
    blindTest: "盲猜テスト",
    visualShort: "見た目の手がかり",
    deception: "誤答のまぎらわしさ",
    safetyShort: "安全",
    improve: "改善案",
    backAdjust: "戻って直す",
    guidelines: "審査基準を見る",
  },
  ko: {
    backHome: "홈으로",
    title: "부분 퀴즈 만들기",
    intro: "사진을 올리고 플레이어가 볼 클로즈업을 표시하세요. 원본과 클로즈업은 브라우저에서 150KB 이하 WebP로 바뀐 뒤 업로드됩니다.",
    quizLanguage: "출제 언어:",
    authorLabel: "작성자 이름",
    authorPlaceholder: "문제에 표시할 이름",
    anonymousAuthor: "익명",
    imageTitle: "이미지와 클로즈업",
    imageHint: "드래그하거나 휠로 확대하세요. 흰 칸이 맞춰야 할 부분입니다.",
    pickImage: "이미지 선택",
    zoom: "확대",
    originalPreviewAlt: "원본 미리보기",
    originalReveal: "원본, 정답 후 공개",
    optionsTitle: "선택지 4개",
    optionsHint: "정답 하나를 표시하세요. 각 선택지에는 틀렸을 때만 보이는 팩폭 한마디가 필요합니다.",
    aiButton: "🤖 AI로 선택지와 팩폭 한마디 만들기",
    aiPending: "AI가 생각 중...",
    optionN: "선택지 {n}",
    optionCorrect: "선택지 {n} · 정답",
    optionText: "선택지 글",
    tauntLabel: "팩폭 한마디",
    publish: "문제 게시",
    compressing: "WebP로 변환 중…",
    moderating: "심사 중…",
    uploading: "업로드 중…",
    saving: "저장 중…",
    signedIn: "로그인됨",
    signOut: "로그아웃",
    signInHint: "게시하려면 로그인하세요. 문제는 계정에 저장됩니다.",
    password: "비밀번호",
    signUp: "가입",
    published: "게시되었습니다",
    viewScore: "점수 상세",
    sizeLine: "클로즈업 {crop}, 원본 {original}",
    cropAlt: "올린 클로즈업",
    originalAlt: "올린 원본",
    cropCaption: "플레이어가 보는 클로즈업",
    originalCaption: "정답 후 공개되는 원본",
    another: "하나 더 만들기",
    scoreTitle: "점수 상세",
    close: "닫기",
    blindSolve: "눈대중으로 풀 수 있는지",
    visualRich: "시각적 특징",
    distractorQuality: "오답 품질",
    community: "안전",
    passed: "통과",
    failedCheck: "실패",
    noVisual: "시각 평가가 아직 없습니다.",
    noDistractor: "오답 평가가 아직 없습니다.",
    aiSuggestion: "AI 제안",
    excellent: "우수",
    acceptable: "합격",
    needAnswer: "먼저 정답 이름을 입력하세요",
    needCrop: "먼저 이미지를 올리고 클로즈업을 표시하세요",
    cropTooSmall: "클로즈업이 너무 작습니다. 칸을 키우세요.",
    aiFailed: "생성에 실패했습니다. 다시 시도하세요.",
    notImage: "이미지 파일을 올리세요",
    passwordShort: "비밀번호는 6자 이상이어야 합니다",
    signedUp: "가입되었습니다. 메일을 확인한 뒤 로그인하세요.",
    authorLength: "작성자 이름은 1~40자입니다",
    needImage: "먼저 이미지를 올리세요",
    cropPending: "자르기 영역이 준비될 때까지 기다리세요",
    optionLength: "선택지 {n} 글은 1~120자입니다",
    tauntLength: "선택지 {n}의 팩폭 한마디는 1~280자입니다",
    needCorrect: "정답 하나를 표시하세요",
    needLogin: "게시하기 전에 로그인하세요",
    cropCompressFail: "클로즈업을 150KB 아래로 줄일 수 없습니다. 영역을 줄이세요.",
    reviewFail: "심사에 실패했습니다. 다시 시도하세요.",
    originalCompressFail: "원본을 150KB 아래로 줄일 수 없습니다. 다른 이미지를 쓰세요.",
    publishFail: "게시하지 못했습니다. 다시 시도하세요.",
    badCredentials: "이메일 또는 비밀번호가 틀립니다",
    emailUnconfirmed: "메일을 확인한 뒤 로그인하세요",
    noPermission: "쓰기 권한이 없습니다. 로그인 상태를 확인하세요.",
    tooLarge: "이미지가 150KB를 넘어 업로드를 중단했습니다",
    webpOnly: "WebP만 업로드할 수 있습니다",
    moderationTitle: "이 문제는 사전 심사를 통과하지 못했습니다",
    safetyZero: "안전 심사에 실패해 점수가 0입니다. 게시되지 않았습니다.",
    scoreLow: "종합 {score}/100으로 60점 미만입니다. 게시되지 않았습니다.",
    adjustHint: "눈대중 결과에 맞춰 자르기를 고치거나, 정답과 오답을 수정한 뒤 다시 게시하세요.",
    blindResult: "AI 눈대중 결과",
    blindTest: "눈대중 테스트",
    visualShort: "시각 단서",
    deception: "오답의 헷갈림",
    safetyShort: "안전",
    improve: "개선 제안",
    backAdjust: "돌아가서 수정",
    guidelines: "심사 기준 보기",
  },
};

function withEnglish(patch: Partial<CreateQuizCopy>): CreateQuizCopy {
  return { ...FULL_COPY.en, ...patch };
}

const REST: Record<Exclude<LanguageCode, "zh-TW" | "zh-CN" | "en" | "es" | "ja" | "ko">, CreateQuizCopy> = {
  pt: withEnglish({
    backHome: "Voltar ao início",
    title: "Criar um quiz de detalhe",
    intro: "Envie uma foto e marque o close que os jogadores verão. As duas imagens viram WebP de até 150KB no navegador antes do envio.",
    quizLanguage: "Idioma da pergunta:",
    authorLabel: "Nome do autor",
    authorPlaceholder: "Nome mostrado na pergunta",
    anonymousAuthor: "Anônimo",
    imageTitle: "Imagem e close",
    imageHint: "Arraste ou use a roda para aproximar. A moldura branca é o detalhe a adivinhar.",
    pickImage: "Escolher imagem",
    optionsTitle: "Quatro opções",
    optionsHint: "Marque uma resposta certa. Cada opção precisa do próprio Comentário Ácido, visto só quando alguém erra.",
    aiButton: "🤖 Gerar opções e comentários ácidos",
    aiPending: "A IA está pensando...",
    optionN: "Opção {n}",
    optionCorrect: "Opção {n} · Certa",
    optionText: "Texto da opção",
    tauntLabel: "Comentário Ácido",
    publish: "Publicar",
    signInHint: "Entre para publicar. A pergunta fica na sua conta.",
    password: "Senha",
    signUp: "Cadastrar",
    published: "Pergunta publicada",
    zoom: "Zoom",
    originalReveal: "Original, revelada ao acertar",
  }),
  ru: withEnglish({
    backHome: "На главную",
    title: "Создать вопрос по фрагменту",
    intro: "Загрузите фото и выделите фрагмент, который увидят игроки. Оба изображения станут WebP до 150КБ в браузере перед загрузкой.",
    quizLanguage: "Язык вопроса:",
    authorLabel: "Имя автора",
    authorPlaceholder: "Имя на вопросе",
    anonymousAuthor: "Аноним",
    imageTitle: "Фото и фрагмент",
    imageHint: "Тяните или крутите колесо. Белая рамка — это фрагмент, который нужно угадать.",
    pickImage: "Выбрать фото",
    optionsTitle: "Четыре варианта",
    optionsHint: "Отметьте один верный ответ. У каждого варианта своя язвительная реплика, её видно только при ошибке.",
    aiButton: "🤖 Сгенерировать варианты и язвительные реплики",
    aiPending: "ИИ думает...",
    optionN: "Вариант {n}",
    optionCorrect: "Вариант {n} · Верный",
    optionText: "Текст варианта",
    tauntLabel: "Язвительная реплика",
    publish: "Опубликовать",
    password: "Пароль",
    signUp: "Регистрация",
    zoom: "Масштаб",
  }),
  de: withEnglish({
    backHome: "Zur Startseite",
    title: "Ein Detailrätsel erstellen",
    intro: "Lade ein Foto hoch und rahme die Nahaufnahme. Beide Bilder werden im Browser zu WebP unter 150KB, bevor sie hochgeladen werden.",
    quizLanguage: "Fragesprache:",
    authorLabel: "Autorenname",
    authorPlaceholder: "Name auf der Frage",
    anonymousAuthor: "Anonym",
    imageTitle: "Bild und Nahaufnahme",
    imageHint: "Ziehen oder scrollen zum Vergrößern. Der weiße Rahmen ist der Ausschnitt, den man erraten muss.",
    pickImage: "Bild wählen",
    optionsTitle: "Vier Optionen",
    optionsHint: "Markiere eine richtige Antwort. Jede Option braucht einen eigenen bissigen Spruch, der nur bei einem Fehler erscheint.",
    aiButton: "🤖 Optionen und bissige Sprüche erzeugen",
    aiPending: "KI denkt nach...",
    optionN: "Option {n}",
    optionCorrect: "Option {n} · Antwort",
    optionText: "Optionstext",
    tauntLabel: "Bissiger Spruch",
    publish: "Veröffentlichen",
    password: "Passwort",
    signUp: "Registrieren",
    zoom: "Zoom",
  }),
  fr: withEnglish({
    backHome: "Retour à l’accueil",
    title: "Créer une énigme en gros plan",
    intro: "Envoie une photo et cadre le gros plan. Les deux images deviennent du WebP sous 150 Ko dans le navigateur avant l’envoi.",
    quizLanguage: "Langue de la question :",
    authorLabel: "Nom de l’auteur",
    authorPlaceholder: "Nom affiché sur la question",
    anonymousAuthor: "Anonyme",
    imageTitle: "Image et gros plan",
    imageHint: "Glisse ou utilise la molette. Le cadre blanc est le détail à deviner.",
    pickImage: "Choisir une image",
    optionsTitle: "Quatre options",
    optionsHint: "Marque une bonne réponse. Chaque option a sa pique acerbe, visible seulement en cas d’erreur.",
    aiButton: "🤖 Générer les options et les piques acerbres",
    aiPending: "L’IA réfléchit...",
    optionN: "Option {n}",
    optionCorrect: "Option {n} · Réponse",
    optionText: "Texte de l’option",
    tauntLabel: "Pique acerbe",
    publish: "Publier",
    password: "Mot de passe",
    signUp: "Inscription",
    zoom: "Zoom",
  }),
  ar: withEnglish({
    backHome: "العودة للرئيسية",
    title: "إنشاء لغز لقطة مقرّبة",
    intro: "ارفع صورة وحدد اللقطة التي سيراها اللاعبون. تتحول الصورتان إلى WebP أقل من 150KB في المتصفح قبل الرفع.",
    quizLanguage: "لغة السؤال:",
    authorLabel: "اسم المؤلف",
    authorPlaceholder: "الاسم الظاهر على السؤال",
    anonymousAuthor: "مجهول",
    imageTitle: "الصورة واللقطة",
    imageHint: "اسحب أو استخدم العجلة للتقريب. الإطار الأبيض هو الجزء المطلوب تخمينه.",
    pickImage: "اختيار صورة",
    optionsTitle: "أربعة خيارات",
    optionsHint: "حدّد إجابة صحيحة واحدة. كل خيار يحتاج تعليقاً لاذعاً يظهر فقط عند الاختيار الخاطئ.",
    aiButton: "🤖 توليد الخيارات والتعليقات اللاذعة",
    aiPending: "الذكاء الاصطناعي يفكر...",
    optionN: "الخيار {n}",
    optionCorrect: "الخيار {n} · الإجابة",
    optionText: "نص الخيار",
    tauntLabel: "تعليق لاذع",
    publish: "نشر السؤال",
    password: "كلمة المرور",
    signUp: "إنشاء حساب",
    zoom: "تكبير",
  }),
  hi: withEnglish({
    backHome: "होम पर जाएँ",
    title: "क्लोज़-अप प्रश्न बनाएँ",
    intro: "एक फ़ोटो अपलोड करें और वह क्लोज़-अप फ़्रेम करें जो खिलाड़ी देखेंगे। दोनों चित्र ब्राउज़र में 150KB से छोटे WebP बनकर अपलोड होते हैं।",
    quizLanguage: "प्रश्न की भाषा:",
    authorLabel: "लेखक का नाम",
    authorPlaceholder: "प्रश्न पर दिखने वाला नाम",
    anonymousAuthor: "अज्ञात",
    imageTitle: "चित्र और क्लोज़-अप",
    imageHint: "खींचें या पहिया घुमाएँ। सफेद फ़्रेम वही हिस्सा है जिसे पहचानना है।",
    pickImage: "चित्र चुनें",
    optionsTitle: "चार विकल्प",
    optionsHint: "एक सही उत्तर चिह्नित करें। हर विकल्प की अपनी तीखी टिप्पणी हो, जो गलत चुनने पर ही दिखे।",
    aiButton: "🤖 विकल्प और तीखी टिप्पणियाँ बनाएँ",
    aiPending: "AI सोच रहा है...",
    optionN: "विकल्प {n}",
    optionCorrect: "विकल्प {n} · उत्तर",
    optionText: "विकल्प का पाठ",
    tauntLabel: "तीखी टिप्पणी",
    publish: "प्रकाशित करें",
    password: "पासवर्ड",
    signUp: "साइन अप",
    zoom: "ज़ूम",
  }),
  bn: withEnglish({
    backHome: "হোমে ফিরুন",
    title: "ক্লোজ-আপ ধাঁধা তৈরি",
    intro: "একটি ছবি আপলোড করে খেলোয়াড়রা যে অংশ দেখবে সেটি ফ্রেম করুন। দুটি ছবিই ব্রাউজারে 150KB-এর নিচের WebP হয়ে আপলোড হয়।",
    quizLanguage: "প্রশ্নের ভাষা:",
    authorLabel: "লেখকের নাম",
    authorPlaceholder: "প্রশ্নে দেখানো নাম",
    anonymousAuthor: "বেনামি",
    imageTitle: "ছবি ও ক্লোজ-আপ",
    imageHint: "টেনে আনুন বা চাকা ঘোরান। সাদা ফ্রেমই অনুমানের অংশ।",
    pickImage: "ছবি বেছে নিন",
    optionsTitle: "চারটি বিকল্প",
    optionsHint: "একটি সঠিক উত্তর চিহ্নিত করুন। প্রতিটি বিকল্পের নিজস্ব কড়া মন্তব্য থাকবে, যা শুধু ভুল বেছে নিলে দেখা যায়।",
    aiButton: "🤖 বিকল্প ও কড়া মন্তব্য তৈরি",
    aiPending: "AI ভাবছে...",
    optionN: "বিকল্প {n}",
    optionCorrect: "বিকল্প {n} · উত্তর",
    optionText: "বিকল্পের লেখা",
    tauntLabel: "কড়া মন্তব্য",
    publish: "প্রকাশ করুন",
    password: "পাসওয়ার্ড",
    signUp: "নিবন্ধন",
    zoom: "জুম",
  }),
  id: withEnglish({
    backHome: "Kembali ke beranda",
    title: "Buat kuis close-up",
    intro: "Unggah foto dan bingkai close-up yang akan dilihat pemain. Kedua gambar diubah menjadi WebP di bawah 150KB di peramban sebelum diunggah.",
    quizLanguage: "Bahasa soal:",
    authorLabel: "Nama pembuat",
    authorPlaceholder: "Nama yang tampil di soal",
    anonymousAuthor: "Anonim",
    imageTitle: "Gambar dan close-up",
    imageHint: "Seret atau gulir untuk memperbesar. Bingkai putih adalah bagian yang harus ditebak.",
    pickImage: "Pilih gambar",
    optionsTitle: "Empat pilihan",
    optionsHint: "Tandai satu jawaban benar. Setiap pilihan butuh Komentar Pedas sendiri, yang hanya terlihat jika salah pilih.",
    aiButton: "🤖 Buat pilihan dan komentar pedas",
    aiPending: "AI sedang berpikir...",
    optionN: "Pilihan {n}",
    optionCorrect: "Pilihan {n} · Jawaban",
    optionText: "Teks pilihan",
    tauntLabel: "Komentar Pedas",
    publish: "Terbitkan",
    password: "Kata sandi",
    signUp: "Daftar",
    zoom: "Perbesar",
  }),
  it: withEnglish({
    backHome: "Torna alla home",
    title: "Crea un quiz ravvicinato",
    intro: "Carica una foto e inquadra il dettaglio. Entrambe le immagini diventano WebP sotto i 150KB nel browser prima del caricamento.",
    quizLanguage: "Lingua della domanda:",
    authorLabel: "Nome dell’autore",
    authorPlaceholder: "Nome mostrato sulla domanda",
    anonymousAuthor: "Anonimo",
    imageTitle: "Immagine e dettaglio",
    imageHint: "Trascina o usa la rotella. La cornice bianca è il dettaglio da indovinare.",
    pickImage: "Scegli immagine",
    optionsTitle: "Quattro opzioni",
    optionsHint: "Segna una risposta giusta. Ogni opzione ha il suo commento tagliente, visibile solo a chi sbaglia.",
    aiButton: "🤖 Genera opzioni e commenti taglienti",
    aiPending: "L’IA sta pensando...",
    optionN: "Opzione {n}",
    optionCorrect: "Opzione {n} · Risposta",
    optionText: "Testo dell’opzione",
    tauntLabel: "Commento tagliente",
    publish: "Pubblica",
    password: "Password",
    signUp: "Registrati",
    zoom: "Zoom",
  }),
  th: withEnglish({
    backHome: "กลับหน้าแรก",
    title: "สร้างโจทย์ภาพใกล้",
    intro: "อัปโหลดรูปแล้วกรอบส่วนที่ผู้เล่นจะเห็น ทั้งสองรูปจะถูกแปลงเป็น WebP ไม่เกิน 150KB ในเบราว์เซอร์ก่อนอัปโหลด",
    quizLanguage: "ภาษาของโจทย์:",
    authorLabel: "ชื่อผู้สร้าง",
    authorPlaceholder: "ชื่อที่แสดงบนโจทย์",
    anonymousAuthor: "ไม่ระบุชื่อ",
    imageTitle: "รูปและภาพใกล้",
    imageHint: "ลากหรือเลื่อนล้อเพื่อซูม กรอบขาวคือส่วนที่ต้องทาย",
    pickImage: "เลือกรูป",
    optionsTitle: "สี่ตัวเลือก",
    optionsHint: "ทำเครื่องหมายคำตอบที่ถูกหนึ่งข้อ ทุกตัวเลือกต้องมีคอมเมนต์แสบของตัวเอง ซึ่งจะเห็นเมื่อเลือกผิด",
    aiButton: "🤖 ให้ AI สร้างตัวเลือกและคอมเมนต์แสบ",
    aiPending: "AI กำลังคิด...",
    optionN: "ตัวเลือก {n}",
    optionCorrect: "ตัวเลือก {n} · คำตอบ",
    optionText: "ข้อความตัวเลือก",
    tauntLabel: "คอมเมนต์แสบ",
    publish: "เผยแพร่",
    password: "รหัสผ่าน",
    signUp: "สมัคร",
    zoom: "ซูม",
  }),
  pl: withEnglish({
    backHome: "Wróć na start",
    title: "Utwórz zagadkę ze zbliżenia",
    intro: "Wgraj zdjęcie i obramuj detal. Oba obrazy stają się WebP poniżej 150KB w przeglądarce przed wysłaniem.",
    quizLanguage: "Język pytania:",
    authorLabel: "Imię autora",
    authorPlaceholder: "Nazwa na pytaniu",
    anonymousAuthor: "Anonim",
    imageTitle: "Obraz i zbliżenie",
    imageHint: "Przeciągnij albo kółkiem przybliż. Biała ramka to fragment do odgadnięcia.",
    pickImage: "Wybierz obraz",
    optionsTitle: "Cztery opcje",
    optionsHint: "Oznacz jedną poprawną odpowiedź. Każda opcja potrzebuje własnego zjadliwego komentarza, widocznego tylko przy pomyłce.",
    aiButton: "🤖 Wygeneruj opcje i zjadliwe komentarze",
    aiPending: "AI myśli...",
    optionN: "Opcja {n}",
    optionCorrect: "Opcja {n} · Odpowiedź",
    optionText: "Tekst opcji",
    tauntLabel: "Zjadliwy komentarz",
    publish: "Opublikuj",
    password: "Hasło",
    signUp: "Rejestracja",
    zoom: "Powiększenie",
  }),
  uk: withEnglish({
    backHome: "На головну",
    title: "Створити питання за фрагментом",
    intro: "Завантажте фото й виділіть фрагмент. Обидва зображення стануть WebP до 150КБ у браузері перед надсиланням.",
    quizLanguage: "Мова питання:",
    authorLabel: "Ім’я автора",
    authorPlaceholder: "Ім’я на питанні",
    anonymousAuthor: "Анонім",
    imageTitle: "Фото і фрагмент",
    imageHint: "Тягніть або крутіть коліщатко. Біла рамка — це фрагмент, який треба вгадати.",
    pickImage: "Обрати фото",
    optionsTitle: "Чотири варіанти",
    optionsHint: "Позначте одну правильну відповідь. Кожен варіант має власну їдку репліку, її видно лише при помилці.",
    aiButton: "🤖 Згенерувати варіанти й їдкі репліки",
    aiPending: "ШІ думає...",
    optionN: "Варіант {n}",
    optionCorrect: "Варіант {n} · Відповідь",
    optionText: "Текст варіанта",
    tauntLabel: "Їдка репліка",
    publish: "Опублікувати",
    password: "Пароль",
    signUp: "Реєстрація",
    zoom: "Масштаб",
  }),
  nl: withEnglish({
    backHome: "Terug naar home",
    title: "Maak een close-upquiz",
    intro: "Upload een foto en kader de close-up. Beide beelden worden in de browser WebP onder 150KB voordat ze worden geüpload.",
    quizLanguage: "Taal van de vraag:",
    authorLabel: "Naam van de maker",
    authorPlaceholder: "Naam op de vraag",
    anonymousAuthor: "Anoniem",
    imageTitle: "Beeld en close-up",
    imageHint: "Sleep of scroll om in te zoomen. Het witte kader is het stuk dat geraden moet worden.",
    pickImage: "Kies een beeld",
    optionsTitle: "Vier opties",
    optionsHint: "Markeer één goed antwoord. Elke optie heeft een eigen venijnige opmerking, alleen zichtbaar bij een fout.",
    aiButton: "🤖 Opties en venijnige opmerkingen maken",
    aiPending: "AI denkt na...",
    optionN: "Optie {n}",
    optionCorrect: "Optie {n} · Antwoord",
    optionText: "Optietekst",
    tauntLabel: "Venijnige opmerking",
    publish: "Publiceren",
    password: "Wachtwoord",
    signUp: "Registreren",
    zoom: "Zoom",
  }),
  el: withEnglish({
    backHome: "Πίσω στην αρχή",
    title: "Φτιάξε ένα κουίζ κοντινού",
    intro: "Ανέβασε μια φωτογραφία και πλαίσιοσε το κοντινό. Και οι δύο εικόνες γίνονται WebP κάτω από 150KB στο πρόγραμμα περιήγησης πριν ανέβουν.",
    quizLanguage: "Γλώσσα ερώτησης:",
    authorLabel: "Όνομα δημιουργού",
    authorPlaceholder: "Όνομα που φαίνεται στην ερώτηση",
    anonymousAuthor: "Ανώνυμος",
    imageTitle: "Εικόνα και κοντινό",
    imageHint: "Σύρε ή κύλησε για ζουμ. Το λευκό πλαίσιο είναι το σημείο που πρέπει να μαντέψουν.",
    pickImage: "Επιλογή εικόνας",
    optionsTitle: "Τέσσερις επιλογές",
    optionsHint: "Σημείωσε μία σωστή απάντηση. Κάθε επιλογή θέλει το δικό της καυστικό σχόλιο, ορατό μόνο σε λάθος επιλογή.",
    aiButton: "🤖 Δημιούργησε επιλογές και καυστικά σχόλια",
    aiPending: "Η ΤΝ σκέφτεται...",
    optionN: "Επιλογή {n}",
    optionCorrect: "Επιλογή {n} · Απάντηση",
    optionText: "Κείμενο επιλογής",
    tauntLabel: "Καυστικό σχόλιο",
    publish: "Δημοσίευση",
    password: "Κωδικός",
    signUp: "Εγγραφή",
    zoom: "Ζουμ",
  }),
  cs: withEnglish({
    backHome: "Zpět domů",
    title: "Vytvořit hádanku z detailu",
    intro: "Nahraj fotku a orámuj detail. Oba obrázky se v prohlížeči změní na WebP pod 150KB ještě před odesláním.",
    quizLanguage: "Jazyk otázky:",
    authorLabel: "Jméno autora",
    authorPlaceholder: "Jméno zobrazené u otázky",
    anonymousAuthor: "Anonym",
    imageTitle: "Obrázek a detail",
    imageHint: "Táhni nebo kolečkem přibliž. Bílý rámeček je část, kterou je třeba uhodnout.",
    pickImage: "Vybrat obrázek",
    optionsTitle: "Čtyři možnosti",
    optionsHint: "Označ jednu správnou odpověď. Každá možnost potřebuje vlastní jízlivou poznámku, kterou uvidí jen ten, kdo se splete.",
    aiButton: "🤖 Vygenerovat možnosti a jízlivé poznámky",
    aiPending: "AI přemýšlí...",
    optionN: "Možnost {n}",
    optionCorrect: "Možnost {n} · Odpověď",
    optionText: "Text možnosti",
    tauntLabel: "Jízlivá poznámka",
    publish: "Publikovat",
    password: "Heslo",
    signUp: "Registrace",
    zoom: "Přiblížení",
  }),
  sv: withEnglish({
    backHome: "Tillbaka hem",
    title: "Skapa en närbildsfråga",
    intro: "Ladda upp en bild och rama in närbilden. Båda bilderna blir WebP under 150KB i webbläsaren innan de laddas upp.",
    quizLanguage: "Frågans språk:",
    authorLabel: "Författarnamn",
    authorPlaceholder: "Namn som visas på frågan",
    anonymousAuthor: "Anonym",
    imageTitle: "Bild och närbild",
    imageHint: "Dra eller skrolla för att zooma. Den vita ramen är delen som ska gissas.",
    pickImage: "Välj bild",
    optionsTitle: "Fyra alternativ",
    optionsHint: "Markera ett rätt svar. Varje alternativ behöver en egen vass kommentar, som bara syns vid fel val.",
    aiButton: "🤖 Skapa alternativ och vassa kommentarer",
    aiPending: "AI tänker...",
    optionN: "Alternativ {n}",
    optionCorrect: "Alternativ {n} · Svar",
    optionText: "Alternativtext",
    tauntLabel: "Vass kommentar",
    publish: "Publicera",
    password: "Lösenord",
    signUp: "Registrera",
    zoom: "Zoom",
  }),
  ro: withEnglish({
    backHome: "Înapoi acasă",
    title: "Creează un quiz de detaliu",
    intro: "Încarcă o poză și încadrează detaliul. Ambele imagini devin WebP sub 150KB în browser înainte de încărcare.",
    quizLanguage: "Limba întrebării:",
    authorLabel: "Numele autorului",
    authorPlaceholder: "Numele afișat pe întrebare",
    anonymousAuthor: "Anonim",
    imageTitle: "Imagine și detaliu",
    imageHint: "Trage sau folosește rotița. Cadrul alb este porțiunea de ghicit.",
    pickImage: "Alege imaginea",
    optionsTitle: "Patru opțiuni",
    optionsHint: "Marchează un răspuns corect. Fiecare opțiune are propriul comentariu acid, vizibil doar la o alegere greșită.",
    aiButton: "🤖 Generează opțiuni și comentarii acide",
    aiPending: "AI se gândește...",
    optionN: "Opțiunea {n}",
    optionCorrect: "Opțiunea {n} · Răspuns",
    optionText: "Textul opțiunii",
    tauntLabel: "Comentariu acid",
    publish: "Publică",
    password: "Parolă",
    signUp: "Înregistrare",
    zoom: "Zoom",
  }),
  hu: withEnglish({
    backHome: "Vissza a főoldalra",
    title: "Közeli kvíz készítése",
    intro: "Tölts fel egy képet, és keretezd be a részletet. Mindkét kép a böngészőben 150KB alatti WebP lesz feltöltés előtt.",
    quizLanguage: "A kérdés nyelve:",
    authorLabel: "Szerző neve",
    authorPlaceholder: "A kérdésen látható név",
    anonymousAuthor: "Névtelen",
    imageTitle: "Kép és közeli",
    imageHint: "Húzd vagy görgess a nagyításhoz. A fehér keret a kitalálandó rész.",
    pickImage: "Kép választása",
    optionsTitle: "Négy lehetőség",
    optionsHint: "Jelölj egy helyes választ. Minden lehetőségnek saját csípős megjegyzése van, amit csak téves választáskor látni.",
    aiButton: "🤖 Lehetőségek és csípős megjegyzések",
    aiPending: "Az AI gondolkodik...",
    optionN: "{n}. lehetőség",
    optionCorrect: "{n}. lehetőség · Válasz",
    optionText: "A lehetőség szövege",
    tauntLabel: "Csípős megjegyzés",
    publish: "Közzététel",
    password: "Jelszó",
    signUp: "Regisztráció",
    zoom: "Nagyítás",
  }),
  he: withEnglish({
    backHome: "חזרה הביתה",
    title: "יצירת חידת תקריב",
    intro: "העלו תמונה ומסגרו את התקריב. שתי התמונות הופכות ל-WebP מתחת ל-150KB בדפדפן לפני ההעלאה.",
    quizLanguage: "שפת השאלה:",
    authorLabel: "שם היוצר",
    authorPlaceholder: "השם שמופיע על השאלה",
    anonymousAuthor: "אנונימי",
    imageTitle: "תמונה ותקריב",
    imageHint: "גררו או גלגלו כדי להתקרב. המסגרת הלבנה היא החלק שצריך לנחש.",
    pickImage: "בחירת תמונה",
    optionsTitle: "ארבע אפשרויות",
    optionsHint: "סמנו תשובה נכונה אחת. לכל אפשרות יש הערה עוקצנית משלה, שמופיעה רק בבחירה שגויה.",
    aiButton: "🤖 יצירת אפשרויות והערות עוקצניות",
    aiPending: "הבינה חושבת...",
    optionN: "אפשרות {n}",
    optionCorrect: "אפשרות {n} · תשובה",
    optionText: "טקסט האפשרות",
    tauntLabel: "הערה עוקצנית",
    publish: "פרסום",
    password: "סיסמה",
    signUp: "הרשמה",
    zoom: "זום",
  }),
  ms: withEnglish({
    backHome: "Kembali ke laman utama",
    title: "Cipta kuiz close-up",
    intro: "Muat naik foto dan bingkaikan close-up. Kedua-dua imej ditukar kepada WebP di bawah 150KB dalam pelayar sebelum dimuat naik.",
    quizLanguage: "Bahasa soalan:",
    authorLabel: "Nama penulis",
    authorPlaceholder: "Nama yang dipaparkan pada soalan",
    anonymousAuthor: "Tanpa nama",
    imageTitle: "Imej dan close-up",
    imageHint: "Seret atau tatal untuk zum. Bingkai putih ialah bahagian yang perlu diteka.",
    pickImage: "Pilih imej",
    optionsTitle: "Empat pilihan",
    optionsHint: "Tandakan satu jawapan betul. Setiap pilihan perlukan Komen pedas sendiri, yang hanya kelihatan jika tersalah pilih.",
    aiButton: "🤖 Jana pilihan dan komen pedas",
    aiPending: "AI sedang berfikir...",
    optionN: "Pilihan {n}",
    optionCorrect: "Pilihan {n} · Jawapan",
    optionText: "Teks pilihan",
    tauntLabel: "Komen pedas",
    publish: "Terbitkan",
    password: "Kata laluan",
    signUp: "Daftar",
    zoom: "Zum",
  }),
  fa: withEnglish({
    backHome: "بازگشت به خانه",
    title: "ساخت معمای نمای نزدیک",
    intro: "یک عکس بگذارید و نمای نزدیک را قاب کنید. هر دو تصویر پیش از بارگذاری در مرورگر به WebP زیر ۱۵۰کیلوبایت تبدیل می‌شوند.",
    quizLanguage: "زبان سؤال:",
    authorLabel: "نام نویسنده",
    authorPlaceholder: "نامی که روی سؤال دیده می‌شود",
    anonymousAuthor: "ناشناس",
    imageTitle: "تصویر و نمای نزدیک",
    imageHint: "بکشید یا بچرخانید. قاب سفید همان بخشی است که باید حدس زده شود.",
    pickImage: "انتخاب تصویر",
    optionsTitle: "چهار گزینه",
    optionsHint: "یک پاسخ درست را مشخص کنید. هر گزینه نظر نیش‌دار خودش را دارد و فقط هنگام انتخاب اشتباه دیده می‌شود.",
    aiButton: "🤖 ساخت گزینه‌ها و نظرهای نیش‌دار",
    aiPending: "هوش مصنوعی در حال فکر کردن...",
    optionN: "گزینه {n}",
    optionCorrect: "گزینه {n} · پاسخ",
    optionText: "متن گزینه",
    tauntLabel: "نظر نیش‌دار",
    publish: "انتشار",
    password: "گذرواژه",
    signUp: "ثبت‌نام",
    zoom: "بزرگ‌نمایی",
  }),
  fil: withEnglish({
    backHome: "Bumalik sa home",
    title: "Gumawa ng close-up na quiz",
    intro: "Mag-upload ng larawan at i-frame ang close-up. Parehong magiging WebP na wala pang 150KB sa browser bago i-upload.",
    quizLanguage: "Wika ng tanong:",
    authorLabel: "Pangalan ng may-akda",
    authorPlaceholder: "Pangalang lalabas sa tanong",
    anonymousAuthor: "Hindi pinangalanan",
    imageTitle: "Larawan at close-up",
    imageHint: "I-drag o i-scroll para lumapit. Ang puting frame ang bahaging hulaan.",
    pickImage: "Pumili ng larawan",
    optionsTitle: "Apat na pagpipilian",
    optionsHint: "Markahan ang isang tamang sagot. Bawat pagpipilian ay may sariling matulis na komento, na makikita lang kapag mali ang pinili.",
    aiButton: "🤖 Gumawa ng mga pagpipilian at matulis na komento",
    aiPending: "Nag-iisip ang AI...",
    optionN: "Pagpipilian {n}",
    optionCorrect: "Pagpipilian {n} · Sagot",
    optionText: "Teksto ng pagpipilian",
    tauntLabel: "Matulis na Komento",
    publish: "I-publish",
    password: "Password",
    signUp: "Mag-sign up",
    zoom: "Zoom",
  }),
  da: withEnglish({
    backHome: "Tilbage til forsiden",
    title: "Lav en nærbilledquiz",
    intro: "Upload et foto og ram nærbilledet ind. Begge billeder bliver til WebP under 150KB i browseren før upload.",
    quizLanguage: "Spørgsmålets sprog:",
    authorLabel: "Forfatternavn",
    authorPlaceholder: "Navn der vises på spørgsmålet",
    anonymousAuthor: "Anonym",
    imageTitle: "Billede og nærbillede",
    imageHint: "Træk eller scroll for at zoome. Den hvide ramme er det, der skal gættes.",
    pickImage: "Vælg billede",
    optionsTitle: "Fire muligheder",
    optionsHint: "Markér ét rigtigt svar. Hver mulighed skal have sin egen skarpe kommentar, som kun ses ved et forkert valg.",
    aiButton: "🤖 Lav muligheder og skarpe kommentarer",
    aiPending: "AI tænker...",
    optionN: "Mulighed {n}",
    optionCorrect: "Mulighed {n} · Svar",
    optionText: "Mulighedstekst",
    tauntLabel: "Skarp kommentar",
    publish: "Udgiv",
    password: "Adgangskode",
    signUp: "Opret konto",
    zoom: "Zoom",
  }),
  fi: withEnglish({
    backHome: "Takaisin kotiin",
    title: "Tee lähikuva-arvoitus",
    intro: "Lataa kuva ja rajaa lähikuva. Molemmat kuvat muuttuvat alle 150KB:n WebP:ksi selaimessa ennen lähetystä.",
    quizLanguage: "Kysymyksen kieli:",
    authorLabel: "Tekijän nimi",
    authorPlaceholder: "Kysymyksessä näkyvä nimi",
    anonymousAuthor: "Nimetön",
    imageTitle: "Kuva ja lähikuva",
    imageHint: "Vedä tai vieritä lähentääksesi. Valkoinen kehys on arvattava kohta.",
    pickImage: "Valitse kuva",
    optionsTitle: "Neljä vaihtoehtoa",
    optionsHint: "Merkitse yksi oikea vastaus. Jokaisella vaihtoehdolla on oma tuhma kommenttinsa, joka näkyy vain väärässä valinnassa.",
    aiButton: "🤖 Luo vaihtoehdot ja tuhmat kommentit",
    aiPending: "Tekoäly miettii...",
    optionN: "Vaihtoehto {n}",
    optionCorrect: "Vaihtoehto {n} · Vastaus",
    optionText: "Vaihtoehdon teksti",
    tauntLabel: "Tuhma kommentti",
    publish: "Julkaise",
    password: "Salasana",
    signUp: "Rekisteröidy",
    zoom: "Lähennä",
  }),
};

export function createCopyFor(language: LanguageCode): CreateQuizCopy {
  if (language in FULL_COPY) return FULL_COPY[language as keyof typeof FULL_COPY];
  return REST[language as keyof typeof REST] ?? FULL_COPY.en;
}
