import type { LanguageCode } from "@/lib/languages";

export const UI_KEYS = [
  "title",
  "tagline",
  "casual",
  "casualHint",
  "challenge",
  "challengeHint",
  "pk",
  "pkHint",
  "create",
  "leaderboard",
  "login",
  "streak",
  "correct",
  "wrong",
  "next",
  "report",
  "shame",
  "thinPool",
  "publishAs",
  "drawing",
] as const;

export type UiKey = (typeof UI_KEYS)[number];

type UiCopy = Record<UiKey, string>;

export const UI_COPY: Record<LanguageCode, UiCopy> = {
  "zh-TW": {
    title: "你瞎了嗎？",
    tagline: "只給你一張特寫。看走眼就準備被嘲。",
    casual: "休閒模式",
    casualHint: "無壓力休閒答題，答錯看迷因毒舌吐槽",
    challenge: "挑戰模式",
    challengeHint: "10秒極速累分，答錯或超時就結束",
    pk: "PK模式",
    pkHint: "隨機 1v1，或開房間跟朋友一起猜",
    create: "我要出題",
    leaderboard: "排行榜",
    login: "登入",
    streak: "連勝 {n}",
    correct: "答對了！",
    wrong: "答錯了",
    next: "下一題",
    report: "回報糾錯",
    shame: "屈辱戰報",
    thinPool: "這個語言的題目還不多，已混入其他語言的題目。",
    publishAs: "出題語言：{name}",
    drawing: "正在抽題…",
  },
  "zh-CN": {
    title: "你瞎了吗？",
    tagline: "只给你一张特写。看走眼就准备被嘲。",
    casual: "休闲模式",
    casualHint: "没有压力地答题，答错就看毒舌吐槽",
    challenge: "挑战模式",
    challengeHint: "10秒极速累分，答错或超时就结束",
    pk: "PK模式",
    pkHint: "随机对决，或开房间和朋友一起猜",
    create: "我要出题",
    leaderboard: "排行榜",
    login: "登录",
    streak: "连胜 {n}",
    correct: "答对了！",
    wrong: "答错了",
    next: "下一题",
    report: "回报纠错",
    shame: "屈辱战报",
    thinPool: "这个语言的题目还不多，已混入其他语言的题目。",
    publishAs: "出题语言：{name}",
    drawing: "正在抽题…",
  },
  en: {
    title: "Are You Blind?",
    tagline: "One extreme close-up. Miss it and get roasted.",
    casual: "Casual",
    casualHint: "No pressure. A wrong guess gets a meme roast.",
    challenge: "Challenge",
    challengeHint: "Score in 10 seconds. A miss or timeout ends the run.",
    pk: "PK Mode",
    pkHint: "Random 1v1, or open a room with friends.",
    create: "Make a Quiz",
    leaderboard: "Leaderboard",
    login: "Log in",
    streak: "{n} streak",
    correct: "Correct!",
    wrong: "Wrong",
    next: "Next",
    report: "Report",
    shame: "Shame Report",
    thinPool: "This language still has few quizzes, so others are mixed in.",
    publishAs: "Quiz language: {name}",
    drawing: "Drawing a quiz…",
  },
  es: {
    title: "¿Estás ciego?",
    tagline: "Solo un primer plano. Si fallas, prepárate para la burla.",
    casual: "Modo casual",
    casualHint: "Sin presión. Si fallas, llega la burla.",
    challenge: "Modo desafío",
    challengeHint: "10 segundos para sumar. Un fallo o el tiempo acaba la partida.",
    pk: "Modo PK",
    pkHint: "Duelo al azar, o una sala con amigos.",
    create: "Crear pregunta",
    leaderboard: "Clasificación",
    login: "Entrar",
    streak: "Racha {n}",
    correct: "¡Correcto!",
    wrong: "Incorrecto",
    next: "Siguiente",
    report: "Reportar error",
    shame: "Informe de humillación",
    thinPool: "Este idioma aún tiene pocas preguntas, así que se mezclan otras.",
    publishAs: "Idioma de la pregunta: {name}",
    drawing: "Sacando una pregunta…",
  },
  ja: {
    title: "目が節穴？",
    tagline: "超アップ写真一枚。外したら煽られる。",
    casual: "カジュアル",
    casualHint: "気軽に回答。外すと毒舌ミーム。",
    challenge: "チャレンジ",
    challengeHint: "10秒で得点。不正解か時間切れで終了。",
    pk: "PKモード",
    pkHint: "ランダム対戦か、友達と部屋を作る。",
    create: "問題を作る",
    leaderboard: "ランキング",
    login: "ログイン",
    streak: "{n} 連勝",
    correct: "正解！",
    wrong: "不正解",
    next: "次の問題",
    report: "誤りを報告",
    shame: "屈辱レポート",
    thinPool: "この言語の問題はまだ少ないので、他の言語も混ぜています。",
    publishAs: "出題言語：{name}",
    drawing: "問題を引いています…",
  },
  ko: {
    title: "눈 감았냐?",
    tagline: "극단 클로즈업 한 장. 틀리면 놀림당한다.",
    casual: "캐주얼 모드",
    casualHint: "부담 없이 풀고, 틀리면 독설 밈.",
    challenge: "챌린지 모드",
    challengeHint: "10초 안에 점수. 오답이나 시간 초과면 종료.",
    pk: "PK 모드",
    pkHint: "랜덤 대결, 또는 친구와 방 만들기.",
    create: "문제 내기",
    leaderboard: "랭킹",
    login: "로그인",
    streak: "{n}연승",
    correct: "정답!",
    wrong: "오답",
    next: "다음 문제",
    report: "오류 신고",
    shame: "굴욕 리포트",
    thinPool: "이 언어 문제가 아직 적어 다른 언어 문제를 섞었습니다.",
    publishAs: "출제 언어: {name}",
    drawing: "문제를 뽑는 중…",
  },
  pt: {
    title: "Você está cego?",
    tagline: "Só um close. Errou, prepara o roast.",
    casual: "Modo casual",
    casualHint: "Sem pressão. Errou, vem a zoação.",
    challenge: "Modo desafio",
    challengeHint: "10 segundos para pontuar. Erro ou tempo esgota a rodada.",
    pk: "Modo PK",
    pkHint: "Duelo aleatório ou sala com amigos.",
    create: "Criar pergunta",
    leaderboard: "Ranking",
    login: "Entrar",
    streak: "Sequência {n}",
    correct: "Acertou!",
    wrong: "Errou",
    next: "Próxima",
    report: "Reportar erro",
    shame: "Relato da humilhação",
    thinPool: "Este idioma ainda tem poucas perguntas, então outras entram na mistura.",
    publishAs: "Idioma da pergunta: {name}",
    drawing: "Sorteando uma pergunta…",
  },
  ru: {
    title: "Ты ослеп?",
    tagline: "Один макроснимок. Промахнёшься — получишь насмешку.",
    casual: "Свободный режим",
    casualHint: "Без давления. Ошибка — язвительный мем.",
    challenge: "Режим вызова",
    challengeHint: "10 секунд на очки. Ошибка или таймер — конец.",
    pk: "Режим PK",
    pkHint: "Случайная дуэль или комната с друзьями.",
    create: "Создать вопрос",
    leaderboard: "Рейтинг",
    login: "Войти",
    streak: "Серия {n}",
    correct: "Верно!",
    wrong: "Мимо",
    next: "Дальше",
    report: "Сообщить об ошибке",
    shame: "Позорный отчёт",
    thinPool: "Вопросов на этом языке мало, поэтому подмешаны другие.",
    publishAs: "Язык вопроса: {name}",
    drawing: "Тянем вопрос…",
  },
  de: {
    title: "Bist du blind?",
    tagline: "Nur eine Makroaufnahme. Daneben, und der Spott kommt.",
    casual: "Freizeitmodus",
    casualHint: "Ohne Druck. Falsch, und der Spruch sitzt.",
    challenge: "Herausforderung",
    challengeHint: "10 Sekunden punkten. Fehler oder Zeit ab, Runde vorbei.",
    pk: "PK-Modus",
    pkHint: "Zufallsduell oder Raum mit Freunden.",
    create: "Frage erstellen",
    leaderboard: "Rangliste",
    login: "Anmelden",
    streak: "Serie {n}",
    correct: "Richtig!",
    wrong: "Falsch",
    next: "Nächste",
    report: "Fehler melden",
    shame: "Schmachbericht",
    thinPool: "Für diese Sprache gibt es noch wenige Fragen, andere werden gemischt.",
    publishAs: "Fragesprache: {name}",
    drawing: "Frage wird gezogen…",
  },
  fr: {
    title: "T’es aveugle ?",
    tagline: "Un gros plan. À côté, et la vanne tombe.",
    casual: "Mode détente",
    casualHint: "Sans pression. Raté, place à la vanne.",
    challenge: "Mode défi",
    challengeHint: "10 secondes pour marquer. Erreur ou temps écoulé, c’est fini.",
    pk: "Mode PK",
    pkHint: "Duel aléatoire, ou une salle entre amis.",
    create: "Créer une question",
    leaderboard: "Classement",
    login: "Connexion",
    streak: "Série {n}",
    correct: "Correct !",
    wrong: "Raté",
    next: "Suivante",
    report: "Signaler une erreur",
    shame: "Rapport d’humiliation",
    thinPool: "Cette langue a encore peu de questions, d’autres sont mélangées.",
    publishAs: "Langue de la question : {name}",
    drawing: "Tirage d’une question…",
  },
  ar: {
    title: "أأنت أعمى؟",
    tagline: "لقطة مقرّبة واحدة. إن أخطأت، فالسخرية جاهزة.",
    casual: "الوضع العادي",
    casualHint: "بلا ضغط. الخطأ يجلب تعليقاً لاذعاً.",
    challenge: "وضع التحدي",
    challengeHint: "10 ثوانٍ للنقاط. خطأ أو انتهاء الوقت ينهي الجولة.",
    pk: "وضع المبارزة",
    pkHint: "مواجهة عشوائية، أو غرفة مع الأصدقاء.",
    create: "أريد طرح سؤال",
    leaderboard: "لوحة الصدارة",
    login: "تسجيل الدخول",
    streak: "سلسلة {n}",
    correct: "إجابة صحيحة!",
    wrong: "إجابة خاطئة",
    next: "السؤال التالي",
    report: "الإبلاغ عن خطأ",
    shame: "تقرير الخزي",
    thinPool: "أسئلة هذه اللغة قليلة، لذلك أُضيفت أسئلة بلغات أخرى.",
    publishAs: "لغة السؤال: {name}",
    drawing: "جارٍ سحب سؤال…",
  },
  hi: {
    title: "क्या तुम अंधे हो?",
    tagline: "सिर्फ़ एक क्लोज़-अप। चूके तो ताना तैयार है।",
    casual: "कैज़ुअल मोड",
    casualHint: "बिना दबाव के। गलत जवाब पर तंज।",
    challenge: "चैलेंज मोड",
    challengeHint: "10 सेकंड में अंक। गलत या समय समाप्त तो खेल खत्म।",
    pk: "PK मोड",
    pkHint: "रैंडम मुकाबला, या दोस्तों के साथ कमरा।",
    create: "सवाल बनाऊँ",
    leaderboard: "रैंकिंग",
    login: "लॉग इन",
    streak: "{n} की लय",
    correct: "सही!",
    wrong: "गलत",
    next: "अगला सवाल",
    report: "गलती बताएँ",
    shame: "शर्मनाक रिपोर्ट",
    thinPool: "इस भाषा के सवाल अभी कम हैं, इसलिए दूसरी भाषाएँ मिलाई गई हैं।",
    publishAs: "प्रश्न की भाषा: {name}",
    drawing: "सवाल निकाला जा रहा है…",
  },
  bn: {
    title: "তুমি কি অন্ধ?",
    tagline: "শুধু একটা ক্লোজ-আপ। ভুল হলে তামাশা তৈরি।",
    casual: "ক্যাজুয়াল মোড",
    casualHint: "চাপ নেই। ভুল উত্তরে কষা মন্তব্য।",
    challenge: "চ্যালেঞ্জ মোড",
    challengeHint: "১০ সেকেন্ডে পয়েন্ট। ভুল বা সময় শেষ হলে খেলা শেষ।",
    pk: "PK মোড",
    pkHint: "র‍্যান্ডম লড়াই, বা বন্ধুদের সঙ্গে রুম।",
    create: "প্রশ্ন বানাব",
    leaderboard: "র‍্যাঙ্কিং",
    login: "লগ ইন",
    streak: "{n} ধারা",
    correct: "ঠিক!",
    wrong: "ভুল",
    next: "পরের প্রশ্ন",
    report: "ভুল জানান",
    shame: "অপমানের রিপোর্ট",
    thinPool: "এই ভাষায় প্রশ্ন এখনও কম, তাই অন্য ভাষা মেশানো হয়েছে।",
    publishAs: "প্রশ্নের ভাষা: {name}",
    drawing: "প্রশ্ন তোলা হচ্ছে…",
  },
  id: {
    title: "Kamu buta, ya?",
    tagline: "Cuma satu close-up. Salah, siap-siap diejek.",
    casual: "Mode santai",
    casualHint: "Tanpa tekanan. Salah, dapat sindiran.",
    challenge: "Mode tantangan",
    challengeHint: "10 detik untuk skor. Salah atau waktu habis, selesai.",
    pk: "Mode PK",
    pkHint: "Duel acak, atau buat ruang bersama teman.",
    create: "Buat soal",
    leaderboard: "Papan peringkat",
    login: "Masuk",
    streak: "Beruntun {n}",
    correct: "Benar!",
    wrong: "Salah",
    next: "Soal berikutnya",
    report: "Laporkan kesalahan",
    shame: "Laporan malu",
    thinPool: "Soal bahasa ini masih sedikit, jadi soal lain dicampur.",
    publishAs: "Bahasa soal: {name}",
    drawing: "Mengambil soal…",
  },
  it: {
    title: "Sei cieco?",
    tagline: "Solo un primo piano. Sbagli, e arriva la battuta.",
    casual: "Modalità casual",
    casualHint: "Zero pressione. Sbagli, e parte la battuta.",
    challenge: "Modalità sfida",
    challengeHint: "10 secondi per i punti. Errore o tempo, fine.",
    pk: "Modalità PK",
    pkHint: "Duello casuale o stanza con gli amici.",
    create: "Crea una domanda",
    leaderboard: "Classifica",
    login: "Accedi",
    streak: "Serie {n}",
    correct: "Giusto!",
    wrong: "Sbagliato",
    next: "Prossima",
    report: "Segnala un errore",
    shame: "Report dell’umiliazione",
    thinPool: "Questa lingua ha ancora poche domande, quindi ne mescoliamo altre.",
    publishAs: "Lingua della domanda: {name}",
    drawing: "Pesca di una domanda…",
  },
  th: {
    title: "ตาบอดหรือไง?",
    tagline: "ให้ดูใกล้แค่ภาพเดียว พลาดแล้วเตรียมโดนแซว",
    casual: "โหมดชิล",
    casualHint: "ไม่กดดัน ตอบผิดได้คำแซวแสบ ๆ",
    challenge: "โหมดท้าทาย",
    challengeHint: "10 วินาทีเก็บคะแนน ผิดหรือหมดเวลาคือจบ",
    pk: "โหมด PK",
    pkHint: "สุ่มดวล หรือเปิดห้องกับเพื่อน",
    create: "ฉันจะออกโจทย์",
    leaderboard: "อันดับ",
    login: "เข้าสู่ระบบ",
    streak: "ชนะติด {n}",
    correct: "ตอบถูก!",
    wrong: "ตอบผิด",
    next: "ข้อถัดไป",
    report: "แจ้งข้อผิดพลาด",
    shame: "รายงานความอาย",
    thinPool: "โจทย์ภาษานี้ยังน้อย เลยผสมภาษาอื่นเข้ามา",
    publishAs: "ภาษาของโจทย์: {name}",
    drawing: "กำลังสุ่มโจทย์…",
  },
  pl: {
    title: "Oślepełeś?",
    tagline: "Jedno zbliżenie. Pudło i jest drwina.",
    casual: "Tryb luźny",
    casualHint: "Bez presji. Błąd oznacza ciętą ripostę.",
    challenge: "Tryb wyzwania",
    challengeHint: "10 sekund na punkty. Błąd albo czas kończy grę.",
    pk: "Tryb PK",
    pkHint: "Losowy pojedynek albo pokój ze znajomymi.",
    create: "Ułóż pytanie",
    leaderboard: "Ranking",
    login: "Zaloguj się",
    streak: "Seria {n}",
    correct: "Dobrze!",
    wrong: "Źle",
    next: "Następne",
    report: "Zgłoś błąd",
    shame: "Raport wstydu",
    thinPool: "Tego języka jest jeszcze mało, więc mieszamy inne pytania.",
    publishAs: "Język pytania: {name}",
    drawing: "Losowanie pytania…",
  },
  uk: {
    title: "Ти осліп?",
    tagline: "Одне макро. Промах — і готуйся до кпину.",
    casual: "Вільний режим",
    casualHint: "Без тиску. Помилка — їдкий жарт.",
    challenge: "Режим виклику",
    challengeHint: "10 секунд на бали. Помилка або час — кінець.",
    pk: "Режим PK",
    pkHint: "Випадковий двобій або кімната з друзями.",
    create: "Скласти питання",
    leaderboard: "Рейтинг",
    login: "Увійти",
    streak: "Серія {n}",
    correct: "Вірно!",
    wrong: "Невірно",
    next: "Далі",
    report: "Повідомити про помилку",
    shame: "Звіт приниження",
    thinPool: "Питань цією мовою ще мало, тож домішано інші.",
    publishAs: "Мова питання: {name}",
    drawing: "Тягнемо питання…",
  },
  nl: {
    title: "Ben je blind?",
    tagline: "Eén close-up. Mis je hem, dan komt de sneer.",
    casual: "Casualmodus",
    casualHint: "Geen druk. Fout, en de sneer volgt.",
    challenge: "Uitdagingsmodus",
    challengeHint: "10 seconden scoren. Fout of tijd om, dan klaar.",
    pk: "PK-modus",
    pkHint: "Willekeurig duel of een kamer met vrienden.",
    create: "Vraag maken",
    leaderboard: "Ranglijst",
    login: "Inloggen",
    streak: "Reeks {n}",
    correct: "Goed!",
    wrong: "Fout",
    next: "Volgende",
    report: "Fout melden",
    shame: "Schaamterapport",
    thinPool: "Deze taal heeft nog weinig vragen, dus andere worden gemengd.",
    publishAs: "Taal van de vraag: {name}",
    drawing: "Vraag wordt getrokken…",
  },
  el: {
    title: "Τυφλώθηκες;",
    tagline: "Ένα κοντινό πλάνο. Αστοχία και έρχεται το πείραγμα.",
    casual: "Χαλαρή λειτουργία",
    casualHint: "Χωρίς πίεση. Λάθος, και πέφτει το σαρκαστικό σχόλιο.",
    challenge: "Λειτουργία πρόκλησης",
    challengeHint: "10 δευτερόλεπτα για πόντους. Λάθος ή χρόνος, τέλος.",
    pk: "Λειτουργία PK",
    pkHint: "Τυχαία μονομαχία ή δωμάτιο με φίλους.",
    create: "Θέλω να φτιάξω ερώτηση",
    leaderboard: "Κατάταξη",
    login: "Σύνδεση",
    streak: "Σερί {n}",
    correct: "Σωστά!",
    wrong: "Λάθος",
    next: "Επόμενη",
    report: "Αναφορά λάθους",
    shame: "Αναφορά ταπείνωσης",
    thinPool: "Αυτή η γλώσσα έχει ακόμα λίγες ερωτήσεις, οπότε μπλέκονται άλλες.",
    publishAs: "Γλώσσα ερώτησης: {name}",
    drawing: "Τραβάμε ερώτηση…",
  },
  cs: {
    title: "Oslepl jsi?",
    tagline: "Jeden detail. Mineš a přijde jízlivost.",
    casual: "Volný režim",
    casualHint: "Bez tlaku. Špatně, a přijde jedovatá poznámka.",
    challenge: "Režim výzvy",
    challengeHint: "10 sekund na body. Chyba nebo čas, konec.",
    pk: "Režim PK",
    pkHint: "Náhodný souboj nebo místnost s přáteli.",
    create: "Chci zadat otázku",
    leaderboard: "Žebříček",
    login: "Přihlásit se",
    streak: "Série {n}",
    correct: "Správně!",
    wrong: "Špatně",
    next: "Další",
    report: "Nahlásit chybu",
    shame: "Zpráva o pokoření",
    thinPool: "V tomhle jazyce je otázek málo, proto přimícháváme další.",
    publishAs: "Jazyk otázky: {name}",
    drawing: "Taháme otázku…",
  },
  sv: {
    title: "Är du blind?",
    tagline: "En närbild. Missar du får du ett gliring.",
    casual: "Fritidsläge",
    casualHint: "Inget tryck. Fel svar ger en giftig kommentar.",
    challenge: "Utmaningsläge",
    challengeHint: "10 sekunder poäng. Fel eller tid ute, slut.",
    pk: "PK-läge",
    pkHint: "Slumpduell eller rum med vänner.",
    create: "Skapa en fråga",
    leaderboard: "Topplista",
    login: "Logga in",
    streak: "{n} i rad",
    correct: "Rätt!",
    wrong: "Fel",
    next: "Nästa",
    report: "Rapportera fel",
    shame: "Skamrapport",
    thinPool: "Det här språket har få frågor, så andra blandas in.",
    publishAs: "Frågans språk: {name}",
    drawing: "Drar en fråga…",
  },
  ro: {
    title: "Ești orb?",
    tagline: "Un singur prim-plan. Greșești și vine zeflemeaua.",
    casual: "Mod relaxat",
    casualHint: "Fără presiune. Greșeală, comentariu acid.",
    challenge: "Mod provocare",
    challengeHint: "10 secunde pentru puncte. Greșeală sau timp, gata.",
    pk: "Mod PK",
    pkHint: "Duel la întâmplare sau cameră cu prietenii.",
    create: "Vreau să dau o întrebare",
    leaderboard: "Clasament",
    login: "Autentificare",
    streak: "Serie {n}",
    correct: "Corect!",
    wrong: "Greșit",
    next: "Următoarea",
    report: "Raportează o eroare",
    shame: "Raport de umilință",
    thinPool: "Limba asta are încă puține întrebări, așa că amestecăm altele.",
    publishAs: "Limba întrebării: {name}",
    drawing: "Se extrage o întrebare…",
  },
  hu: {
    title: "Megvakultál?",
    tagline: "Egy közeli kép. Mellé, és jön a csípős megjegyzés.",
    casual: "Laza mód",
    casualHint: "Nyomás nélkül. Rossz válasz, csípős poén.",
    challenge: "Kihívás mód",
    challengeHint: "10 másodperc a pontra. Hiba vagy idő, vége.",
    pk: "PK mód",
    pkHint: "Véletlen párbaj, vagy szoba a barátokkal.",
    create: "Kérdést írok",
    leaderboard: "Ranglista",
    login: "Belépés",
    streak: "{n} sorozat",
    correct: "Talált!",
    wrong: "Mellé",
    next: "Következő",
    report: "Hiba jelentése",
    shame: "Megaláztatási jelentés",
    thinPool: "Ezen a nyelven még kevés a kérdés, ezért másokat keverünk hozzá.",
    publishAs: "A kérdés nyelve: {name}",
    drawing: "Kérdés húzása…",
  },
  he: {
    title: "התעוורת?",
    tagline: "תקריב אחד. פספוס, והעוקצנות בדרך.",
    casual: "מצב רגוע",
    casualHint: "בלי לחץ. טעות מביאה עוקצנות.",
    challenge: "מצב אתגר",
    challengeHint: "10 שניות לנקודות. טעות או זמן, נגמר.",
    pk: "מצב PK",
    pkHint: "דו-קרב אקראי, או חדר עם חברים.",
    create: "אני רוצה לחבר שאלה",
    leaderboard: "טבלת מובילים",
    login: "התחברות",
    streak: "רצף {n}",
    correct: "נכון!",
    wrong: "טעות",
    next: "השאלה הבאה",
    report: "דיווח על טעות",
    shame: "דוח השפלה",
    thinPool: "בשפה הזו עדיין מעט שאלות, אז ערבבנו שאלות אחרות.",
    publishAs: "שפת השאלה: {name}",
    drawing: "שולפים שאלה…",
  },
  ms: {
    title: "Buta ke?",
    tagline: "Satu close-up saja. Salah, sedia diejek.",
    casual: "Mod santai",
    casualHint: "Tanpa tekanan. Salah, dapat sindiran.",
    challenge: "Mod cabaran",
    challengeHint: "10 saat untuk mata. Salah atau masa habis, tamat.",
    pk: "Mod PK",
    pkHint: "Duel rawak, atau bilik bersama kawan.",
    create: "Saya nak buat soalan",
    leaderboard: "Carta kedudukan",
    login: "Log masuk",
    streak: "Berturut {n}",
    correct: "Betul!",
    wrong: "Salah",
    next: "Seterusnya",
    report: "Laporkan ralat",
    shame: "Laporan malu",
    thinPool: "Soalan bahasa ini masih sedikit, jadi soalan lain dicampur.",
    publishAs: "Bahasa soalan: {name}",
    drawing: "Sedang memilih soalan…",
  },
  fa: {
    title: "کور شدی؟",
    tagline: "فقط یک نمای نزدیک. اشتباه کنی، مسخره آماده است.",
    casual: "حالت عادی",
    casualHint: "بدون فشار. جواب غلط، طعنه تند.",
    challenge: "حالت چالش",
    challengeHint: "۱۰ ثانیه برای امتیاز. غلط یا پایان زمان، بازی تمام.",
    pk: "حالت PK",
    pkHint: "دوئل تصادفی، یا اتاق با دوستان.",
    create: "می‌خواهم سؤال بدهم",
    leaderboard: "جدول امتیازات",
    login: "ورود",
    streak: "برد پیاپی {n}",
    correct: "درست بود!",
    wrong: "غلط بود",
    next: "سؤال بعدی",
    report: "گزارش خطا",
    shame: "گزارش تحقیر",
    thinPool: "سؤال‌های این زبان هنوز کم است، پس سؤال‌های دیگر قاطی شده‌اند.",
    publishAs: "زبان سؤال: {name}",
    drawing: "در حال کشیدن سؤال…",
  },
  fil: {
    title: "Bulag ka ba?",
    tagline: "Isang close-up lang. Mali, handa na ang tukso.",
    casual: "Casual mode",
    casualHint: "Walang pressure. Mali, may masasakit na biro.",
    challenge: "Challenge mode",
    challengeHint: "10 segundo para sa puntos. Mali o timeout, tapos.",
    pk: "PK mode",
    pkHint: "Random na laban, o silid kasama ang mga kaibigan.",
    create: "Gagawa ako ng tanong",
    leaderboard: "Leaderboard",
    login: "Mag-log in",
    streak: "Sunod-sunod na {n}",
    correct: "Tama!",
    wrong: "Mali",
    next: "Susunod",
    report: "Iulat ang mali",
    shame: "Ulat ng kahihiyan",
    thinPool: "Konti pa ang tanong sa wikang ito, kaya may halong iba.",
    publishAs: "Wika ng tanong: {name}",
    drawing: "Kumukuha ng tanong…",
  },
  da: {
    title: "Er du blind?",
    tagline: "Ét nærbillede. Rammer du forkert, kommer drilleriet.",
    casual: "Afslappet tilstand",
    casualHint: "Intet pres. Forkert svar giver en skarp bemærkning.",
    challenge: "Udfordring",
    challengeHint: "10 sekunder til point. Fejl eller tid, så er det slut.",
    pk: "PK-tilstand",
    pkHint: "Tilfældig duel eller et rum med venner.",
    create: "Jeg vil lave et spørgsmål",
    leaderboard: "Rangliste",
    login: "Log ind",
    streak: "Stime på {n}",
    correct: "Rigtigt!",
    wrong: "Forkert",
    next: "Næste",
    report: "Rapportér en fejl",
    shame: "Ydmygelsesrapport",
    thinPool: "Dette sprog har stadig få spørgsmål, så andre er blandet ind.",
    publishAs: "Spørgsmålets sprog: {name}",
    drawing: "Trækker et spørgsmål…",
  },
  fi: {
    title: "Oletko sokea?",
    tagline: "Yksi lähikuva. Ohi, ja piikki tulee.",
    casual: "Rento tila",
    casualHint: "Ei painetta. Väärästä vastauksesta tulee piikki.",
    challenge: "Haastetila",
    challengeHint: "10 sekuntia pisteisiin. Virhe tai aika, peli ohi.",
    pk: "PK-tila",
    pkHint: "Satunnainen kaksintaistelu tai huone kavereiden kanssa.",
    create: "Haluan tehdä kysymyksen",
    leaderboard: "Tulostaulu",
    login: "Kirjaudu",
    streak: "Putki {n}",
    correct: "Oikein!",
    wrong: "Väärin",
    next: "Seuraava",
    report: "Ilmoita virheestä",
    shame: "Nolousraportti",
    thinPool: "Tällä kielellä on vielä vähän kysymyksiä, joten mukaan sekoitetaan muita.",
    publishAs: "Kysymyksen kieli: {name}",
    drawing: "Arvotaan kysymystä…",
  },
};

export function translate(language: LanguageCode, key: UiKey, vars?: Record<string, string | number>): string {
  const template = UI_COPY[language][key] ?? UI_COPY.en[key];
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (match, name: string) => {
    const value = vars[name];
    return value === undefined ? match : String(value);
  });
}
