import type { LanguageCode } from "@/lib/languages";

export type HonorCardCopy = {
  title: string;
  rankPrefix: string;
  rankSuffix: string;
  maxStreak: string;
  points: string;
  leaderboardBtn: string;
  unranked: string;
  loading: string;
  signInHint: string;
};

export type ThemeCardCopy = {
  title: string;
  subtitle: string;
};

export type ChallengeModeCopy = {
  badge: string;
  title: string;
  rule1: string;
  rule2: string;
  rule3: string;
  startBtn: string;
  backHome: string;
};

export type PkLobbyCopy = {
  backHome: string;
  title: string;
  subtitle: string;
  randomMatchTitle: string;
  randomMatchDesc: string;
  vipPrivilege: string;
  createRoomTitle: string;
  createRoomDesc: string;
  createRoomReady: string;
  checkingHost: string;
  creatingCode: string;
  joinRoomTitle: string;
  joinRoomDesc: string;
  roomCodePlaceholder: string;
  enterRoomBtn: string;
  checkingLogin: string;
  loginHint: string;
  matching: string;
  searched: string;
  finding: string;
  startingSoon: string;
  cancelMatch: string;
};

export type UiSections = {
  honorCard: HonorCardCopy;
  themeCard: ThemeCardCopy;
  challengeMode: ChallengeModeCopy;
  pkLobby: PkLobbyCopy;
};

function pack(
  honorCard: HonorCardCopy,
  themeCard: ThemeCardCopy,
  challengeMode: ChallengeModeCopy,
  pkLobby: PkLobbyCopy,
): UiSections {
  return { honorCard, themeCard, challengeMode, pkLobby };
}

const UI_SECTIONS: Record<LanguageCode, UiSections> = {
  "zh-TW": pack(
    {
      title: "個人榮譽卡",
      rankPrefix: "第",
      rankSuffix: "名",
      maxStreak: "最高連勝",
      points: "分",
      leaderboardBtn: "排行榜",
      unranked: "尚未進入挑戰榜，立即挑戰飆分！",
      loading: "正在讀取戰績…",
      signInHint: "登入以記錄挑戰模式積分與名次",
    },
    { title: "主題專案包", subtitle: "即將登場 / 垂直題庫" },
    {
      badge: "CHALLENGE",
      title: "挑戰模式",
      rule1: "每題只有 10 秒。",
      rule2: "答對得分是 1000 加上剩餘時間加權，越快越高。",
      rule3: "答錯或時間到，這一局立刻結束。",
      startBtn: "開始挑戰",
      backHome: "返回首頁",
    },
    {
      backHome: "返回首頁",
      title: "多人 PK 對決",
      subtitle: "隨機找一位對手，或用 4 碼房號跟朋友一起猜。",
      randomMatchTitle: "隨機匹配 (1v1)",
      randomMatchDesc: "立即搜尋全球線上玩家，滿 2 人極速開賽對決。",
      vipPrivilege: "VIP 專屬開房特權",
      createRoomTitle: "創建好友房",
      createRoomDesc: "私人好友房只開放給 VIP。",
      createRoomReady: "產生 4 碼房號，2 到 4 人由房長開賽。",
      checkingHost: "正在確認開房資格…",
      creatingCode: "正在生成房號…",
      joinRoomTitle: "加入房間",
      joinRoomDesc: "輸入正確的 4 碼房號就能加入，不限 VIP。",
      roomCodePlaceholder: "4 碼房號",
      enterRoomBtn: "進入房間",
      checkingLogin: "正在確認登入狀態…",
      loginHint: "登入 Google 之後才能開始隨機匹配。加入好友房只要有房號即可。",
      matching: "隨機匹配",
      searched: "已搜尋：{time}",
      finding: "正在尋找實力相當的對手...",
      startingSoon: "即將開賽",
      cancelMatch: "取消匹配",
    },
  ),
  "zh-CN": pack(
    {
      title: "个人荣誉卡",
      rankPrefix: "第",
      rankSuffix: "名",
      maxStreak: "最高连胜",
      points: "分",
      leaderboardBtn: "排行榜",
      unranked: "还没进入挑战榜，马上挑战飙分！",
      loading: "正在读取战绩…",
      signInHint: "登录以记录挑战模式积分与名次",
    },
    { title: "主题专案包", subtitle: "即将登场 / 垂直题库" },
    {
      badge: "CHALLENGE",
      title: "挑战模式",
      rule1: "每题只有 10 秒。",
      rule2: "答对得分是 1000 加上剩余时间加权，越快越高。",
      rule3: "答错或时间到，这一局立刻结束。",
      startBtn: "开始挑战",
      backHome: "返回首页",
    },
    {
      backHome: "返回首页",
      title: "多人 PK 对决",
      subtitle: "随机找一位对手，或用 4 位房号和朋友一起猜。",
      randomMatchTitle: "随机匹配 (1v1)",
      randomMatchDesc: "立即搜索全球在线玩家，满 2 人极速开赛。",
      vipPrivilege: "VIP 专属开房特权",
      createRoomTitle: "创建好友房",
      createRoomDesc: "私人好友房只对 VIP 开放。",
      createRoomReady: "生成 4 位房号，2 到 4 人由房主开赛。",
      checkingHost: "正在确认开房资格…",
      creatingCode: "正在生成房号…",
      joinRoomTitle: "加入房间",
      joinRoomDesc: "输入正确的 4 位房号即可加入，不限 VIP。",
      roomCodePlaceholder: "4 位房号",
      enterRoomBtn: "进入房间",
      checkingLogin: "正在确认登录状态…",
      loginHint: "登录 Google 之后才能开始随机匹配。加入好友房只要有房号即可。",
      matching: "随机匹配",
      searched: "已搜索：{time}",
      finding: "正在寻找实力相当的对手...",
      startingSoon: "即将开赛",
      cancelMatch: "取消匹配",
    },
  ),
  en: pack(
    {
      title: "Honor Card",
      rankPrefix: "Rank #",
      rankSuffix: "",
      maxStreak: "Best Streak",
      points: "pts",
      leaderboardBtn: "Leaderboard",
      unranked: "Not ranked yet. Start a challenge!",
      loading: "Loading your record…",
      signInHint: "Log in to save challenge score and rank",
    },
    { title: "Theme Packs", subtitle: "Coming Soon / Curated Decks" },
    {
      badge: "CHALLENGE",
      title: "Challenge Mode",
      rule1: "Only 10 seconds per question.",
      rule2: "Score 1000 + remaining time bonus. Faster is better.",
      rule3: "One wrong guess or timeout ends the run immediately.",
      startBtn: "Start Challenge",
      backHome: "Back to Home",
    },
    {
      backHome: "Back to Home",
      title: "Multiplayer PK",
      subtitle: "Match a random player or play with friends via 4-digit code.",
      randomMatchTitle: "Quick Match (1v1)",
      randomMatchDesc: "Find online players worldwide. 2 players to start.",
      vipPrivilege: "VIP Host Exclusive",
      createRoomTitle: "Create Private Room",
      createRoomDesc: "Private rooms are only available for VIPs.",
      createRoomReady: "Get a 4-digit code. The host starts with 2–4 players.",
      checkingHost: "Checking host access…",
      creatingCode: "Creating a room code…",
      joinRoomTitle: "Join Room",
      joinRoomDesc: "Enter a 4-digit code to join. Open to all.",
      roomCodePlaceholder: "4-digit code",
      enterRoomBtn: "Join",
      checkingLogin: "Checking sign-in…",
      loginHint: "Sign in with Google to quick match. A room code is enough to join friends.",
      matching: "Quick Match",
      searched: "Searching: {time}",
      finding: "Looking for a fair opponent...",
      startingSoon: "Starting",
      cancelMatch: "Cancel",
    },
  ),
  es: pack(
    {
      title: "Tarjeta de honor",
      rankPrefix: "Puesto",
      rankSuffix: "",
      maxStreak: "Mejor racha",
      points: "pts",
      leaderboardBtn: "Clasificación",
      unranked: "Aún sin puesto. ¡Empieza un desafío!",
      loading: "Cargando tu marca…",
      signInHint: "Entra para guardar puntos y puesto",
    },
    { title: "Paquetes temáticos", subtitle: "Próximamente / Mazos curados" },
    {
      badge: "CHALLENGE",
      title: "Modo desafío",
      rule1: "Solo 10 segundos por pregunta.",
      rule2: "Acertar suma 1000 más el tiempo restante. Más rápido, más puntos.",
      rule3: "Un fallo o el tiempo acaba la partida al instante.",
      startBtn: "Empezar desafío",
      backHome: "Volver al inicio",
    },
    {
      backHome: "Volver al inicio",
      title: "PK multijugador",
      subtitle: "Busca un rival al azar o juega con amigos con un código de 4 dígitos.",
      randomMatchTitle: "Emparejamiento rápido (1v1)",
      randomMatchDesc: "Busca jugadores en línea. Empieza con 2 personas.",
      vipPrivilege: "Anfitrión VIP",
      createRoomTitle: "Crear sala privada",
      createRoomDesc: "Las salas privadas son solo para VIP.",
      createRoomReady: "Código de 4 dígitos. El anfitrión inicia con 2 a 4 jugadores.",
      checkingHost: "Comprobando el permiso…",
      creatingCode: "Creando el código…",
      joinRoomTitle: "Unirse a la sala",
      joinRoomDesc: "Escribe el código de 4 dígitos. Abierto para todos.",
      roomCodePlaceholder: "Código de 4",
      enterRoomBtn: "Entrar",
      checkingLogin: "Comprobando la sesión…",
      loginHint: "Entra con Google para el emparejamiento. Para amigos basta el código.",
      matching: "Emparejando",
      searched: "Buscando: {time}",
      finding: "Buscando un rival parejo...",
      startingSoon: "Va a empezar",
      cancelMatch: "Cancelar",
    },
  ),
  ja: pack(
    {
      title: "名誉カード",
      rankPrefix: "第",
      rankSuffix: "位",
      maxStreak: "最高連勝",
      points: "点",
      leaderboardBtn: "ランキング",
      unranked: "まだ圏外。チャレンジで得点しよう！",
      loading: "戦績を読み込み中…",
      signInHint: "ログインすると得点と順位が残ります",
    },
    { title: "テーマパック", subtitle: "近日公開 / 特集問題" },
    {
      badge: "CHALLENGE",
      title: "チャレンジモード",
      rule1: "1問につき10秒だけ。",
      rule2: "正解は1000点＋残り時間ボーナス。速いほど高い。",
      rule3: "不正解か時間切れで、その回は即終了。",
      startBtn: "チャレンジ開始",
      backHome: "ホームへ戻る",
    },
    {
      backHome: "ホームへ戻る",
      title: "マルチPK",
      subtitle: "ランダムな相手か、4桁の部屋番号で友達と遊ぶ。",
      randomMatchTitle: "ランダムマッチ (1v1)",
      randomMatchDesc: "世界のオンライン相手を検索。2人で即開始。",
      vipPrivilege: "VIP専用の部屋作成",
      createRoomTitle: "フレンド部屋を作る",
      createRoomDesc: "プライベート部屋はVIPだけ。",
      createRoomReady: "4桁の番号を発行。2〜4人でホストが開始。",
      checkingHost: "作成権限を確認中…",
      creatingCode: "部屋番号を作成中…",
      joinRoomTitle: "部屋に入る",
      joinRoomDesc: "正しい4桁を入力すれば誰でも参加できます。",
      roomCodePlaceholder: "4桁の番号",
      enterRoomBtn: "入室",
      checkingLogin: "ログイン状態を確認中…",
      loginHint: "ランダムマッチはGoogleログイン後。友達の部屋は番号だけで入れます。",
      matching: "マッチング",
      searched: "検索中：{time}",
      finding: "近い実力の相手を探しています...",
      startingSoon: "まもなく開始",
      cancelMatch: "キャンセル",
    },
  ),
  ko: pack(
    {
      title: "명예 카드",
      rankPrefix: "",
      rankSuffix: "위",
      maxStreak: "최고 연승",
      points: "점",
      leaderboardBtn: "랭킹",
      unranked: "아직 순위권 밖. 챌린지로 점수를 올려 보세요!",
      loading: "전적을 불러오는 중…",
      signInHint: "로그인하면 점수와 순위가 저장됩니다",
    },
    { title: "테마 팩", subtitle: "곧 공개 / 큐레이션 문제" },
    {
      badge: "CHALLENGE",
      title: "챌린지 모드",
      rule1: "한 문제당 10초뿐입니다.",
      rule2: "정답은 1000점 + 남은 시간 보너스. 빠를수록 높습니다.",
      rule3: "오답이거나 시간이 끝나면 그 판은 즉시 종료.",
      startBtn: "챌린지 시작",
      backHome: "홈으로",
    },
    {
      backHome: "홈으로",
      title: "멀티 PK",
      subtitle: "랜덤 상대를 찾거나, 4자리 방 번호로 친구와 함께.",
      randomMatchTitle: "랜덤 매칭 (1v1)",
      randomMatchDesc: "전 세계 온라인 플레이어를 검색. 2명이면 바로 시작.",
      vipPrivilege: "VIP 전용 방 만들기",
      createRoomTitle: "친구 방 만들기",
      createRoomDesc: "비공개 방은 VIP만 만들 수 있습니다.",
      createRoomReady: "4자리 번호를 만듭니다. 2–4명, 방장이 시작.",
      checkingHost: "방 만들기 권한 확인 중…",
      creatingCode: "방 번호 생성 중…",
      joinRoomTitle: "방 참가",
      joinRoomDesc: "올바른 4자리 번호면 누구나 들어올 수 있습니다.",
      roomCodePlaceholder: "4자리 번호",
      enterRoomBtn: "입장",
      checkingLogin: "로그인 상태 확인 중…",
      loginHint: "랜덤 매칭은 Google 로그인 후. 친구 방은 번호만 있으면 됩니다.",
      matching: "매칭 중",
      searched: "검색：{time}",
      finding: "실력이 비슷한 상대를 찾는 중...",
      startingSoon: "곧 시작",
      cancelMatch: "취소",
    },
  ),
  pt: pack(
    {
      title: "Cartão de honra",
      rankPrefix: "Lugar",
      rankSuffix: "",
      maxStreak: "Melhor sequência",
      points: "pts",
      leaderboardBtn: "Ranking",
      unranked: "Ainda sem lugar. Comece um desafio!",
      loading: "Carregando seu recorde…",
      signInHint: "Entre para guardar pontos e posição",
    },
    { title: "Pacotes temáticos", subtitle: "Em breve / Baralhos curados" },
    {
      badge: "CHALLENGE",
      title: "Modo desafio",
      rule1: "Só 10 segundos por pergunta.",
      rule2: "Acerto vale 1000 mais o tempo restante. Mais rápido, mais pontos.",
      rule3: "Um erro ou o tempo acaba a rodada na hora.",
      startBtn: "Começar desafio",
      backHome: "Voltar ao início",
    },
    {
      backHome: "Voltar ao início",
      title: "PK multijogador",
      subtitle: "Ache um rival aleatório ou jogue com amigos num código de 4 dígitos.",
      randomMatchTitle: "Partida rápida (1v1)",
      randomMatchDesc: "Procura jogadores online. Começa com 2 pessoas.",
      vipPrivilege: "Anfitrião VIP",
      createRoomTitle: "Criar sala privada",
      createRoomDesc: "Salas privadas são só para VIP.",
      createRoomReady: "Código de 4 dígitos. O anfitrião começa com 2 a 4 jogadores.",
      checkingHost: "Verificando permissão…",
      creatingCode: "Gerando o código…",
      joinRoomTitle: "Entrar na sala",
      joinRoomDesc: "Digite o código de 4 dígitos. Aberto para todos.",
      roomCodePlaceholder: "Código de 4",
      enterRoomBtn: "Entrar",
      checkingLogin: "Verificando login…",
      loginHint: "Entre com o Google para a partida rápida. Para amigos, basta o código.",
      matching: "Procurando",
      searched: "Buscando: {time}",
      finding: "Procurando um rival parelho...",
      startingSoon: "Começando",
      cancelMatch: "Cancelar",
    },
  ),
  ru: pack(
    {
      title: "Карта почёта",
      rankPrefix: "Место",
      rankSuffix: "",
      maxStreak: "Лучшая серия",
      points: "очк.",
      leaderboardBtn: "Рейтинг",
      unranked: "Пока без места. Начни вызов!",
      loading: "Загружаем результат…",
      signInHint: "Войди, чтобы сохранить очки и место",
    },
    { title: "Тематические наборы", subtitle: "Скоро / Подобранные колоды" },
    {
      badge: "CHALLENGE",
      title: "Режим вызова",
      rule1: "На вопрос только 10 секунд.",
      rule2: "Верный ответ: 1000 плюс бонус за остаток времени. Быстрее — выше.",
      rule3: "Ошибка или таймер сразу заканчивают попытку.",
      startBtn: "Начать вызов",
      backHome: "На главную",
    },
    {
      backHome: "На главную",
      title: "Мультиплеер PK",
      subtitle: "Случайный соперник или друзья по 4-значному коду.",
      randomMatchTitle: "Быстрый матч (1v1)",
      randomMatchDesc: "Ищем игроков онлайн. Старт с 2 человек.",
      vipPrivilege: "Комната только для VIP",
      createRoomTitle: "Создать комнату",
      createRoomDesc: "Личные комнаты доступны только VIP.",
      createRoomReady: "Код из 4 знаков. Хост начинает при 2–4 игроках.",
      checkingHost: "Проверяем право создать комнату…",
      creatingCode: "Создаём код…",
      joinRoomTitle: "Войти в комнату",
      joinRoomDesc: "Введите верный 4-значный код. Для всех.",
      roomCodePlaceholder: "Код из 4",
      enterRoomBtn: "Войти",
      checkingLogin: "Проверяем вход…",
      loginHint: "Для случайного матча войдите через Google. К друзьям достаточно кода.",
      matching: "Поиск",
      searched: "Поиск: {time}",
      finding: "Ищем равного соперника...",
      startingSoon: "Скоро старт",
      cancelMatch: "Отмена",
    },
  ),
  de: pack(
    {
      title: "Ehrenkarte",
      rankPrefix: "Platz",
      rankSuffix: "",
      maxStreak: "Beste Serie",
      points: "Pkt.",
      leaderboardBtn: "Rangliste",
      unranked: "Noch ohne Platz. Starte eine Herausforderung!",
      loading: "Rekord wird geladen…",
      signInHint: "Anmelden, um Punkte und Platz zu speichern",
    },
    { title: "Themenpakete", subtitle: "Demnächst / Kuratierte Decks" },
    {
      badge: "CHALLENGE",
      title: "Herausforderungsmodus",
      rule1: "Nur 10 Sekunden pro Frage.",
      rule2: "Richtig gibt 1000 plus Restzeit-Bonus. Schneller ist mehr.",
      rule3: "Ein Fehler oder die Zeit beendet die Runde sofort.",
      startBtn: "Herausforderung starten",
      backHome: "Zur Startseite",
    },
    {
      backHome: "Zur Startseite",
      title: "Mehrspieler-PK",
      subtitle: "Zufälliger Gegner oder Freunde mit einem 4-stelligen Code.",
      randomMatchTitle: "Schnellsuche (1v1)",
      randomMatchDesc: "Sucht Spieler weltweit. Start ab 2 Personen.",
      vipPrivilege: "VIP-Gastgeber",
      createRoomTitle: "Privaten Raum erstellen",
      createRoomDesc: "Private Räume gibt es nur für VIPs.",
      createRoomReady: "4-stelliger Code. Der Host startet mit 2–4 Spielern.",
      checkingHost: "Berechtigung wird geprüft…",
      creatingCode: "Code wird erstellt…",
      joinRoomTitle: "Raum beitreten",
      joinRoomDesc: "4-stelligen Code eingeben. Für alle offen.",
      roomCodePlaceholder: "4-stelliger Code",
      enterRoomBtn: "Beitreten",
      checkingLogin: "Anmeldung wird geprüft…",
      loginHint: "Für die Schnellsuche mit Google anmelden. Freunde brauchen nur den Code.",
      matching: "Suche",
      searched: "Suche: {time}",
      finding: "Suche einen passenden Gegner...",
      startingSoon: "Startet gleich",
      cancelMatch: "Abbrechen",
    },
  ),
  fr: pack(
    {
      title: "Carte d’honneur",
      rankPrefix: "Rang",
      rankSuffix: "",
      maxStreak: "Meilleure série",
      points: "pts",
      leaderboardBtn: "Classement",
      unranked: "Pas encore classé. Lance un défi !",
      loading: "Chargement du score…",
      signInHint: "Connecte-toi pour garder points et rang",
    },
    { title: "Packs thématiques", subtitle: "Bientôt / Sélections" },
    {
      badge: "CHALLENGE",
      title: "Mode défi",
      rule1: "10 secondes seulement par question.",
      rule2: "Une bonne réponse vaut 1000 plus le temps restant. Plus vite, plus haut.",
      rule3: "Une erreur ou le temps met fin à la manche aussitôt.",
      startBtn: "Lancer le défi",
      backHome: "Retour à l’accueil",
    },
    {
      backHome: "Retour à l’accueil",
      title: "PK multijoueur",
      subtitle: "Un adversaire au hasard, ou des amis avec un code à 4 chiffres.",
      randomMatchTitle: "Match rapide (1v1)",
      randomMatchDesc: "Cherche des joueurs en ligne. Départ à 2.",
      vipPrivilege: "Hôte VIP",
      createRoomTitle: "Créer un salon privé",
      createRoomDesc: "Les salons privés sont réservés aux VIP.",
      createRoomReady: "Code à 4 chiffres. L’hôte lance avec 2 à 4 joueurs.",
      checkingHost: "Vérification du droit…",
      creatingCode: "Création du code…",
      joinRoomTitle: "Rejoindre un salon",
      joinRoomDesc: "Entre le code à 4 chiffres. Ouvert à tous.",
      roomCodePlaceholder: "Code à 4",
      enterRoomBtn: "Entrer",
      checkingLogin: "Vérification de la connexion…",
      loginHint: "Connecte-toi avec Google pour le match rapide. Le code suffit pour les amis.",
      matching: "Recherche",
      searched: "Recherche : {time}",
      finding: "Recherche d’un adversaire de niveau proche...",
      startingSoon: "Ça commence",
      cancelMatch: "Annuler",
    },
  ),
  ar: pack(
    {
      title: "بطاقة الشرف",
      rankPrefix: "المركز",
      rankSuffix: "",
      maxStreak: "أفضل سلسلة",
      points: "نقطة",
      leaderboardBtn: "لوحة الصدارة",
      unranked: "لست في الترتيب بعد. ابدأ تحديًا!",
      loading: "جارٍ تحميل السجل…",
      signInHint: "سجّل الدخول لحفظ النقاط والمركز",
    },
    { title: "حزم الموضوعات", subtitle: "قريبًا / مجموعات منتقاة" },
    {
      badge: "CHALLENGE",
      title: "وضع التحدي",
      rule1: "عشر ثوانٍ فقط لكل سؤال.",
      rule2: "الإجابة الصحيحة 1000 بالإضافة إلى وقت متبقٍ. الأسرع أعلى.",
      rule3: "خطأ واحد أو انتهاء الوقت ينهي الجولة فورًا.",
      startBtn: "ابدأ التحدي",
      backHome: "العودة للرئيسية",
    },
    {
      backHome: "العودة للرئيسية",
      title: "مبارزة جماعية",
      subtitle: "خصم عشوائي، أو الأصدقاء عبر رمز من 4 أرقام.",
      randomMatchTitle: "مطابقة سريعة (1v1)",
      randomMatchDesc: "ابحث عن لاعبين حول العالم. البدء عند شخصين.",
      vipPrivilege: "إنشاء غرفة للـ VIP",
      createRoomTitle: "إنشاء غرفة خاصة",
      createRoomDesc: "الغرف الخاصة لـ VIP فقط.",
      createRoomReady: "رمز من 4 أرقام. المضيف يبدأ مع 2 إلى 4 لاعبين.",
      checkingHost: "جارٍ التحقق من الصلاحية…",
      creatingCode: "جارٍ إنشاء الرمز…",
      joinRoomTitle: "الانضمام إلى غرفة",
      joinRoomDesc: "أدخل رمزًا صحيحًا من 4 أرقام. متاح للجميع.",
      roomCodePlaceholder: "رمز من 4",
      enterRoomBtn: "ادخل",
      checkingLogin: "جارٍ التحقق من الدخول…",
      loginHint: "المطابقة العشوائية بعد دخول Google. غرفة الأصدقاء تحتاج الرمز فقط.",
      matching: "مطابقة",
      searched: "بحث: {time}",
      finding: "نبحث عن خصم بمستوى قريب...",
      startingSoon: "ستبدأ قريبًا",
      cancelMatch: "إلغاء",
    },
  ),
  hi: pack(
    {
      title: "सम्मान कार्ड",
      rankPrefix: "रैंक",
      rankSuffix: "",
      maxStreak: "सर्वश्रेष्ठ लय",
      points: "अंक",
      leaderboardBtn: "रैंकिंग",
      unranked: "अभी रैंक में नहीं। चैलेंज शुरू करें!",
      loading: "रिकॉर्ड लोड हो रहा है…",
      signInHint: "अंक और रैंक सहेजने के लिए लॉग इन करें",
    },
    { title: "थीम पैक", subtitle: "जल्द आ रहा है / चुने हुए डेक" },
    {
      badge: "CHALLENGE",
      title: "चैलेंज मोड",
      rule1: "हर सवाल के लिए सिर्फ़ 10 सेकंड।",
      rule2: "सही जवाब 1000 और बचे समय का बोनस। जितना तेज़, उतना ज़्यादा।",
      rule3: "एक गलत जवाब या समय समाप्त होते ही यह राउंड खत्म।",
      startBtn: "चैलेंज शुरू करें",
      backHome: "होम पर जाएँ",
    },
    {
      backHome: "होम पर जाएँ",
      title: "मल्टीप्लेयर PK",
      subtitle: "रैंडम प्रतिद्वंद्वी, या 4 अंकों के कोड से दोस्तों के साथ।",
      randomMatchTitle: "क्विक मैच (1v1)",
      randomMatchDesc: "दुनिया भर के ऑनलाइन खिलाड़ी खोजें। 2 लोग होते ही शुरू।",
      vipPrivilege: "VIP होस्ट विशेष",
      createRoomTitle: "प्राइवेट रूम बनाएँ",
      createRoomDesc: "प्राइवेट रूम सिर्फ़ VIP के लिए।",
      createRoomReady: "4 अंकों का कोड। होस्ट 2–4 खिलाड़ियों के साथ शुरू करता है।",
      checkingHost: "अनुमति जाँची जा रही है…",
      creatingCode: "कोड बन रहा है…",
      joinRoomTitle: "रूम में जुड़ें",
      joinRoomDesc: "सही 4 अंकों का कोड डालें। सबके लिए खुला।",
      roomCodePlaceholder: "4 अंकों का कोड",
      enterRoomBtn: "जुड़ें",
      checkingLogin: "लॉगिन जाँचा जा रहा है…",
      loginHint: "क्विक मैच के लिए Google से लॉग इन करें। दोस्तों के रूम के लिए कोड काफी है।",
      matching: "मैच हो रहा है",
      searched: "खोज: {time}",
      finding: "बराबर प्रतिद्वंद्वी खोजा जा रहा है...",
      startingSoon: "शुरू होने वाला है",
      cancelMatch: "रद्द करें",
    },
  ),
  bn: pack(
    {
      title: "সম্মান কার্ড",
      rankPrefix: "র‍্যাঙ্ক",
      rankSuffix: "",
      maxStreak: "সেরা ধারা",
      points: "পয়েন্ট",
      leaderboardBtn: "র‍্যাঙ্কিং",
      unranked: "এখনও র‍্যাঙ্কে নেই। চ্যালেঞ্জ শুরু করুন!",
      loading: "রেকর্ড লোড হচ্ছে…",
      signInHint: "পয়েন্ট ও র‍্যাঙ্ক রাখতে লগ ইন করুন",
    },
    { title: "থিম প্যাক", subtitle: "শীঘ্রই / বাছাই করা ডেক" },
    {
      badge: "CHALLENGE",
      title: "চ্যালেঞ্জ মোড",
      rule1: "প্রতি প্রশ্নে মাত্র ১০ সেকেন্ড।",
      rule2: "সঠিক উত্তর ১০০০ আর বাকি সময়ের বোনাস। যত দ্রুত, তত বেশি।",
      rule3: "একটি ভুল বা সময় শেষ হলে রাউন্ড সঙ্গে সঙ্গে শেষ।",
      startBtn: "চ্যালেঞ্জ শুরু",
      backHome: "হোমে ফিরুন",
    },
    {
      backHome: "হোমে ফিরুন",
      title: "মাল্টিপ্লেয়ার PK",
      subtitle: "র‍্যান্ডম প্রতিপক্ষ, বা ৪ সংখ্যার কোডে বন্ধুদের সঙ্গে।",
      randomMatchTitle: "দ্রুত ম্যাচ (1v1)",
      randomMatchDesc: "বিশ্বের অনলাইন খেলোয়াড় খুঁজুন। ২ জন হলেই শুরু।",
      vipPrivilege: "VIP হোস্ট বিশেষ",
      createRoomTitle: "প্রাইভেট রুম তৈরি",
      createRoomDesc: "প্রাইভেট রুম শুধু VIP-দের জন্য।",
      createRoomReady: "৪ সংখ্যার কোড। হোস্ট ২–৪ জনে শুরু করেন।",
      checkingHost: "অনুমতি যাচাই হচ্ছে…",
      creatingCode: "কোড তৈরি হচ্ছে…",
      joinRoomTitle: "রুমে যোগ দিন",
      joinRoomDesc: "সঠিক ৪ সংখ্যার কোড দিন। সবার জন্য খোলা।",
      roomCodePlaceholder: "৪ সংখ্যার কোড",
      enterRoomBtn: "ঢুকুন",
      checkingLogin: "লগইন যাচাই হচ্ছে…",
      loginHint: "দ্রুত ম্যাচের জন্য Google লগইন লাগবে। বন্ধুর রুমে কোডই যথেষ্ট।",
      matching: "ম্যাচ হচ্ছে",
      searched: "খোঁজা হচ্ছে: {time}",
      finding: "কাছাকাছি প্রতিপক্ষ খোঁজা হচ্ছে...",
      startingSoon: "শুরু হতে চলেছে",
      cancelMatch: "বাতিল",
    },
  ),
  id: pack(
    {
      title: "Kartu kehormatan",
      rankPrefix: "Peringkat",
      rankSuffix: "",
      maxStreak: "Rekor beruntun",
      points: "poin",
      leaderboardBtn: "Papan peringkat",
      unranked: "Belum masuk peringkat. Mulai tantangan!",
      loading: "Memuat catatan…",
      signInHint: "Masuk untuk menyimpan skor dan peringkat",
    },
    { title: "Paket tema", subtitle: "Segera hadir / Dek pilihan" },
    {
      badge: "CHALLENGE",
      title: "Mode tantangan",
      rule1: "Hanya 10 detik per soal.",
      rule2: "Benar mendapat 1000 plus bonus sisa waktu. Makin cepat, makin tinggi.",
      rule3: "Satu salah atau waktu habis langsung mengakhiri ronde.",
      startBtn: "Mulai tantangan",
      backHome: "Kembali ke beranda",
    },
    {
      backHome: "Kembali ke beranda",
      title: "PK multipemain",
      subtitle: "Lawan acak, atau teman lewat kode 4 digit.",
      randomMatchTitle: "Lawan cepat (1v1)",
      randomMatchDesc: "Cari pemain online di dunia. Mulai saat ada 2 orang.",
      vipPrivilege: "Pembuat ruang VIP",
      createRoomTitle: "Buat ruang privat",
      createRoomDesc: "Ruang privat hanya untuk VIP.",
      createRoomReady: "Kode 4 digit. Host mulai dengan 2–4 pemain.",
      checkingHost: "Memeriksa izin…",
      creatingCode: "Membuat kode…",
      joinRoomTitle: "Masuk ruang",
      joinRoomDesc: "Masukkan kode 4 digit yang benar. Terbuka untuk semua.",
      roomCodePlaceholder: "Kode 4 digit",
      enterRoomBtn: "Masuk",
      checkingLogin: "Memeriksa login…",
      loginHint: "Lawan cepat butuh login Google. Ruang teman cukup dengan kode.",
      matching: "Mencari lawan",
      searched: "Mencari: {time}",
      finding: "Mencari lawan yang seimbang...",
      startingSoon: "Segera mulai",
      cancelMatch: "Batal",
    },
  ),
  it: pack(
    {
      title: "Tessera d’onore",
      rankPrefix: "Posto",
      rankSuffix: "",
      maxStreak: "Miglior serie",
      points: "pti",
      leaderboardBtn: "Classifica",
      unranked: "Non sei ancora in classifica. Inizia una sfida!",
      loading: "Caricamento del record…",
      signInHint: "Accedi per salvare punti e posto",
    },
    { title: "Pacchetti a tema", subtitle: "In arrivo / Mazzi curati" },
    {
      badge: "CHALLENGE",
      title: "Modalità sfida",
      rule1: "Solo 10 secondi a domanda.",
      rule2: "Risposta giusta: 1000 più il tempo rimasto. Più veloce, più punti.",
      rule3: "Un errore o il tempo chiudono subito la manche.",
      startBtn: "Inizia la sfida",
      backHome: "Torna alla home",
    },
    {
      backHome: "Torna alla home",
      title: "PK multigiocatore",
      subtitle: "Un avversario a caso, o gli amici con un codice di 4 cifre.",
      randomMatchTitle: "Match rapido (1v1)",
      randomMatchDesc: "Cerca giocatori online. Si parte in 2.",
      vipPrivilege: "Host VIP",
      createRoomTitle: "Crea stanza privata",
      createRoomDesc: "Le stanze private sono solo per i VIP.",
      createRoomReady: "Codice di 4 cifre. L’host parte con 2–4 giocatori.",
      checkingHost: "Controllo del permesso…",
      creatingCode: "Creazione del codice…",
      joinRoomTitle: "Entra nella stanza",
      joinRoomDesc: "Inserisci il codice di 4 cifre. Aperto a tutti.",
      roomCodePlaceholder: "Codice di 4",
      enterRoomBtn: "Entra",
      checkingLogin: "Controllo dell’accesso…",
      loginHint: "Per il match rapido entra con Google. Per gli amici basta il codice.",
      matching: "Ricerca",
      searched: "Ricerca: {time}",
      finding: "Cerco un avversario alla pari...",
      startingSoon: "Si parte",
      cancelMatch: "Annulla",
    },
  ),
  th: pack(
    {
      title: "การ์ดเกียรติยศ",
      rankPrefix: "อันดับ",
      rankSuffix: "",
      maxStreak: "ชนะติดสูงสุด",
      points: "แต้ม",
      leaderboardBtn: "อันดับ",
      unranked: "ยังไม่ติดอันดับ เริ่มท้าทายเลย!",
      loading: "กำลังโหลดสถิติ…",
      signInHint: "เข้าสู่ระบบเพื่อเก็บบัตรคะแนนและอันดับ",
    },
    { title: "ชุดธีม", subtitle: "เร็ว ๆ นี้ / ชุดโจทย์คัดสรร" },
    {
      badge: "CHALLENGE",
      title: "โหมดท้าทาย",
      rule1: "แต่ละข้อมีเวลาแค่ 10 วินาที",
      rule2: "ตอบถูกได้ 1000 บวกโบนัสเวลาที่เหลือ ยิ่งเร็วยิ่งสูง",
      rule3: "ตอบผิดหรือหมดเวลา เกมนี้จบทันที",
      startBtn: "เริ่มท้าทาย",
      backHome: "กลับหน้าแรก",
    },
    {
      backHome: "กลับหน้าแรก",
      title: "PK หลายคน",
      subtitle: "สุ่มคู่ต่อสู้ หรือเล่นกับเพื่อนด้วยรหัส 4 หลัก",
      randomMatchTitle: "จับคู่อัตโนมัติ (1v1)",
      randomMatchDesc: "ค้นหาผู้เล่นออนไลน์ทั่วโลก ครบ 2 คนเริ่มทันที",
      vipPrivilege: "สิทธิ์เปิดห้องของ VIP",
      createRoomTitle: "สร้างห้องส่วนตัว",
      createRoomDesc: "ห้องส่วนตัวเปิดให้เฉพาะ VIP",
      createRoomReady: "ได้รหัส 4 หลัก หัวห้องเริ่มเมื่อมี 2–4 คน",
      checkingHost: "กำลังตรวจสิทธิ์เปิดห้อง…",
      creatingCode: "กำลังสร้างรหัสห้อง…",
      joinRoomTitle: "เข้าร่วมห้อง",
      joinRoomDesc: "ใส่รหัส 4 หลักที่ถูกต้อง ทุกคนเข้าได้",
      roomCodePlaceholder: "รหัส 4 หลัก",
      enterRoomBtn: "เข้าห้อง",
      checkingLogin: "กำลังตรวจสถานะเข้าสู่ระบบ…",
      loginHint: "จับคู่สุ่มต้องเข้า Google ก่อน ห้องเพื่อนใช้แค่รหัส",
      matching: "กำลังจับคู่",
      searched: "ค้นหาแล้ว: {time}",
      finding: "กำลังหาคู่ที่ฝีมือใกล้กัน...",
      startingSoon: "ใกล้เริ่มแล้ว",
      cancelMatch: "ยกเลิก",
    },
  ),
  pl: pack(
    {
      title: "Karta honoru",
      rankPrefix: "Miejsce",
      rankSuffix: "",
      maxStreak: "Najlepsza seria",
      points: "pkt",
      leaderboardBtn: "Ranking",
      unranked: "Jeszcze bez miejsca. Zacznij wyzwanie!",
      loading: "Wczytywanie wyniku…",
      signInHint: "Zaloguj się, by zachować punkty i miejsce",
    },
    { title: "Paczki tematyczne", subtitle: "Wkrótce / Wybrane talie" },
    {
      badge: "CHALLENGE",
      title: "Tryb wyzwania",
      rule1: "Tylko 10 sekund na pytanie.",
      rule2: "Trafienie to 1000 plus bonus za czas. Im szybciej, tym więcej.",
      rule3: "Błąd albo czas kończy rundę od razu.",
      startBtn: "Zacznij wyzwanie",
      backHome: "Wróć na start",
    },
    {
      backHome: "Wróć na start",
      title: "PK dla wielu graczy",
      subtitle: "Losowy rywal albo znajomi z 4-cyfrowym kodem.",
      randomMatchTitle: "Szybki mecz (1v1)",
      randomMatchDesc: "Szuka graczy online. Start od 2 osób.",
      vipPrivilege: "Prowadzący VIP",
      createRoomTitle: "Utwórz prywatny pokój",
      createRoomDesc: "Prywatne pokoje są tylko dla VIP.",
      createRoomReady: "Kod 4-cyfrowy. Gospodarz startuje przy 2–4 graczach.",
      checkingHost: "Sprawdzanie uprawnień…",
      creatingCode: "Tworzenie kodu…",
      joinRoomTitle: "Dołącz do pokoju",
      joinRoomDesc: "Wpisz poprawny kod 4-cyfrowy. Dla wszystkich.",
      roomCodePlaceholder: "Kod 4-cyfrowy",
      enterRoomBtn: "Wejdź",
      checkingLogin: "Sprawdzanie logowania…",
      loginHint: "Szybki mecz wymaga Google. Do znajomych wystarczy kod.",
      matching: "Szukanie",
      searched: "Szukanie: {time}",
      finding: "Szukam wyrównanego rywala...",
      startingSoon: "Zaraz start",
      cancelMatch: "Anuluj",
    },
  ),
  uk: pack(
    {
      title: "Картка пошани",
      rankPrefix: "Місце",
      rankSuffix: "",
      maxStreak: "Найкраща серія",
      points: "балів",
      leaderboardBtn: "Рейтинг",
      unranked: "Ще без місця. Почни виклик!",
      loading: "Завантажуємо результат…",
      signInHint: "Увійди, щоб зберегти бали й місце",
    },
    { title: "Тематичні набори", subtitle: "Незабаром / Добірки" },
    {
      badge: "CHALLENGE",
      title: "Режим виклику",
      rule1: "Лише 10 секунд на питання.",
      rule2: "Правильна відповідь: 1000 плюс бонус за залишок часу. Швидше — вище.",
      rule3: "Помилка або час одразу завершують спробу.",
      startBtn: "Почати виклик",
      backHome: "На головну",
    },
    {
      backHome: "На головну",
      title: "Мультиплеєр PK",
      subtitle: "Випадковий суперник або друзі за 4-значним кодом.",
      randomMatchTitle: "Швидкий матч (1v1)",
      randomMatchDesc: "Шукаємо гравців онлайн. Старт від 2 осіб.",
      vipPrivilege: "Кімната лише для VIP",
      createRoomTitle: "Створити кімнату",
      createRoomDesc: "Приватні кімнати лише для VIP.",
      createRoomReady: "Код із 4 знаків. Хост починає за 2–4 гравців.",
      checkingHost: "Перевіряємо право…",
      creatingCode: "Створюємо код…",
      joinRoomTitle: "Увійти в кімнату",
      joinRoomDesc: "Введіть правильний 4-значний код. Для всіх.",
      roomCodePlaceholder: "Код із 4",
      enterRoomBtn: "Увійти",
      checkingLogin: "Перевіряємо вхід…",
      loginHint: "Для випадкового матчу увійдіть через Google. До друзів достатньо коду.",
      matching: "Пошук",
      searched: "Пошук: {time}",
      finding: "Шукаємо рівного суперника...",
      startingSoon: "Скоро старт",
      cancelMatch: "Скасувати",
    },
  ),
  nl: pack(
    {
      title: "Erekaart",
      rankPrefix: "Plaats",
      rankSuffix: "",
      maxStreak: "Beste reeks",
      points: "ptn",
      leaderboardBtn: "Ranglijst",
      unranked: "Nog geen plaats. Start een uitdaging!",
      loading: "Record laden…",
      signInHint: "Log in om score en plaats te bewaren",
    },
    { title: "Themapakketten", subtitle: "Binnenkort / Geselecteerde decks" },
    {
      badge: "CHALLENGE",
      title: "Uitdagingsmodus",
      rule1: "Maar 10 seconden per vraag.",
      rule2: "Goed is 1000 plus resterende tijd. Sneller is meer.",
      rule3: "Eén fout of de tijd stopt de ronde meteen.",
      startBtn: "Uitdaging starten",
      backHome: "Terug naar home",
    },
    {
      backHome: "Terug naar home",
      title: "Multiplayer PK",
      subtitle: "Een willekeurige tegenstander, of vrienden met een code van 4 cijfers.",
      randomMatchTitle: "Snelle match (1v1)",
      randomMatchDesc: "Zoekt online spelers. Start bij 2 personen.",
      vipPrivilege: "VIP-host",
      createRoomTitle: "Privékamer maken",
      createRoomDesc: "Privékamers zijn alleen voor VIP’s.",
      createRoomReady: "Code van 4 cijfers. De host start met 2–4 spelers.",
      checkingHost: "Recht controleren…",
      creatingCode: "Code maken…",
      joinRoomTitle: "Kamer joinen",
      joinRoomDesc: "Vul de juiste code van 4 cijfers in. Voor iedereen.",
      roomCodePlaceholder: "Code van 4",
      enterRoomBtn: "Naar binnen",
      checkingLogin: "Login controleren…",
      loginHint: "Voor een snelle match log je in met Google. Vrienden hebben alleen de code nodig.",
      matching: "Zoeken",
      searched: "Zoeken: {time}",
      finding: "Een gelijke tegenstander zoeken...",
      startingSoon: "Begint zo",
      cancelMatch: "Annuleren",
    },
  ),
  el: pack(
    {
      title: "Κάρτα τιμής",
      rankPrefix: "Θέση",
      rankSuffix: "",
      maxStreak: "Καλύτερο σερί",
      points: "βαθ.",
      leaderboardBtn: "Κατάταξη",
      unranked: "Ακόμα εκτός κατάταξης. Ξεκίνα πρόκληση!",
      loading: "Φόρτωση ρεκόρ…",
      signInHint: "Συνδέσου για να μείνουν οι βαθμοί και η θέση",
    },
    { title: "Θεματικά πακέτα", subtitle: "Σύντομα / Επιλεγμένες τράπουλες" },
    {
      badge: "CHALLENGE",
      title: "Λειτουργία πρόκλησης",
      rule1: "Μόνο 10 δευτερόλεπτα ανά ερώτηση.",
      rule2: "Σωστό: 1000 συν μπόνους χρόνου. Πιο γρήγορα, πιο ψηλά.",
      rule3: "Ένα λάθος ή ο χρόνος τελειώνει αμέσως τον γύρο.",
      startBtn: "Έναρξη πρόκλησης",
      backHome: "Πίσω στην αρχή",
    },
    {
      backHome: "Πίσω στην αρχή",
      title: "PK πολλών παικτών",
      subtitle: "Τυχαίος αντίπαλος ή φίλοι με κωδικό 4 ψηφίων.",
      randomMatchTitle: "Γρήγορο ματς (1v1)",
      randomMatchDesc: "Ψάχνει online παίκτες. Έναρξη με 2 άτομα.",
      vipPrivilege: "Οικοδεσπότης VIP",
      createRoomTitle: "Ιδιωτικό δωμάτιο",
      createRoomDesc: "Τα ιδιωτικά δωμάτια είναι μόνο για VIP.",
      createRoomReady: "Κωδικός 4 ψηφίων. Ο οικοδεσπότης ξεκινά με 2–4 παίκτες.",
      checkingHost: "Έλεγχος δικαιώματος…",
      creatingCode: "Δημιουργία κωδικού…",
      joinRoomTitle: "Μπες στο δωμάτιο",
      joinRoomDesc: "Βάλε σωστό κωδικό 4 ψηφίων. Ανοιχτό σε όλους.",
      roomCodePlaceholder: "Κωδικός 4",
      enterRoomBtn: "Είσοδος",
      checkingLogin: "Έλεγχος σύνδεσης…",
      loginHint: "Το γρήγορο ματς θέλει Google. Για φίλους αρκεί ο κωδικός.",
      matching: "Αναζήτηση",
      searched: "Αναζήτηση: {time}",
      finding: "Ψάχνω αντίπαλο κοντά στο επίπεδό σου...",
      startingSoon: "Ξεκινάει",
      cancelMatch: "Ακύρωση",
    },
  ),
  cs: pack(
    {
      title: "Karta cti",
      rankPrefix: "Místo",
      rankSuffix: "",
      maxStreak: "Nejlepší série",
      points: "b.",
      leaderboardBtn: "Žebříček",
      unranked: "Ještě bez místa. Začni výzvu!",
      loading: "Načítání rekordu…",
      signInHint: "Přihlas se, ať zůstanou body a místo",
    },
    { title: "Tématické balíčky", subtitle: "Brzy / Vybrané sady" },
    {
      badge: "CHALLENGE",
      title: "Režim výzvy",
      rule1: "Na otázku jen 10 sekund.",
      rule2: "Správně je 1000 plus bonus za zbývající čas. Rychleji znamená víc.",
      rule3: "Chyba nebo čas hru hned ukončí.",
      startBtn: "Začít výzvu",
      backHome: "Zpět domů",
    },
    {
      backHome: "Zpět domů",
      title: "PK pro více hráčů",
      subtitle: "Náhodný soupeř, nebo přátelé přes 4místný kód.",
      randomMatchTitle: "Rychlý zápas (1v1)",
      randomMatchDesc: "Hledá hráče online. Start od 2 lidí.",
      vipPrivilege: "VIP hostitel",
      createRoomTitle: "Vytvořit soukromou místnost",
      createRoomDesc: "Soukromé místnosti jsou jen pro VIP.",
      createRoomReady: "4místný kód. Host začíná se 2–4 hráči.",
      checkingHost: "Ověřování oprávnění…",
      creatingCode: "Vytváření kódu…",
      joinRoomTitle: "Vstoupit do místnosti",
      joinRoomDesc: "Zadej správný 4místný kód. Pro všechny.",
      roomCodePlaceholder: "4místný kód",
      enterRoomBtn: "Vstoupit",
      checkingLogin: "Ověřování přihlášení…",
      loginHint: "Rychlý zápas chce Google. K přátelům stačí kód.",
      matching: "Hledání",
      searched: "Hledání: {time}",
      finding: "Hledám vyrovnaného soupeře...",
      startingSoon: "Začíná se",
      cancelMatch: "Zrušit",
    },
  ),
  sv: pack(
    {
      title: "Hederskort",
      rankPrefix: "Plats",
      rankSuffix: "",
      maxStreak: "Bästa svit",
      points: "p",
      leaderboardBtn: "Topplista",
      unranked: "Inte rankad än. Starta en utmaning!",
      loading: "Laddar rekord…",
      signInHint: "Logga in för att spara poäng och plats",
    },
    { title: "Temapaket", subtitle: "Kommer snart / Utvalda lekar" },
    {
      badge: "CHALLENGE",
      title: "Utmaningsläge",
      rule1: "Bara 10 sekunder per fråga.",
      rule2: "Rätt ger 1000 plus tidbonus. Snabbare är högre.",
      rule3: "Ett fel eller tiden avslutar rundan direkt.",
      startBtn: "Starta utmaning",
      backHome: "Tillbaka hem",
    },
    {
      backHome: "Tillbaka hem",
      title: "PK för flera",
      subtitle: "En slumpad motståndare, eller vänner med en fyrsiffrig kod.",
      randomMatchTitle: "Snabbmatch (1v1)",
      randomMatchDesc: "Söker spelare online. Start vid 2 personer.",
      vipPrivilege: "VIP-värd",
      createRoomTitle: "Skapa privat rum",
      createRoomDesc: "Privata rum är bara för VIP.",
      createRoomReady: "Fyrsiffrig kod. Värden startar med 2–4 spelare.",
      checkingHost: "Kollar behörighet…",
      creatingCode: "Skapar kod…",
      joinRoomTitle: "Gå med i rum",
      joinRoomDesc: "Skriv rätt fyrsiffrig kod. Öppet för alla.",
      roomCodePlaceholder: "Fyrsiffrig kod",
      enterRoomBtn: "Gå in",
      checkingLogin: "Kollar inloggning…",
      loginHint: "Snabbmatch kräver Google. Vänner behöver bara koden.",
      matching: "Söker",
      searched: "Söker: {time}",
      finding: "Letar efter en jämn motståndare...",
      startingSoon: "Startar snart",
      cancelMatch: "Avbryt",
    },
  ),
  ro: pack(
    {
      title: "Card de onoare",
      rankPrefix: "Locul",
      rankSuffix: "",
      maxStreak: "Cea mai bună serie",
      points: "pct",
      leaderboardBtn: "Clasament",
      unranked: "Încă fără loc. Începe o provocare!",
      loading: "Se încarcă recordul…",
      signInHint: "Autentifică-te ca să rămână punctele și locul",
    },
    { title: "Pachete tematice", subtitle: "În curând / Seturi alese" },
    {
      badge: "CHALLENGE",
      title: "Mod provocare",
      rule1: "Doar 10 secunde pe întrebare.",
      rule2: "Răspunsul bun e 1000 plus timpul rămas. Mai repede, mai mult.",
      rule3: "O greșeală sau timpul încheie runda pe loc.",
      startBtn: "Începe provocarea",
      backHome: "Înapoi acasă",
    },
    {
      backHome: "Înapoi acasă",
      title: "PK cu mai mulți",
      subtitle: "Un adversar la întâmplare, sau prieteni cu un cod de 4 cifre.",
      randomMatchTitle: "Meci rapid (1v1)",
      randomMatchDesc: "Caută jucători online. Start de la 2 persoane.",
      vipPrivilege: "Gazdă VIP",
      createRoomTitle: "Creează cameră privată",
      createRoomDesc: "Camerele private sunt doar pentru VIP.",
      createRoomReady: "Cod de 4 cifre. Gazda pornește cu 2–4 jucători.",
      checkingHost: "Se verifică dreptul…",
      creatingCode: "Se creează codul…",
      joinRoomTitle: "Intră în cameră",
      joinRoomDesc: "Introdu codul corect de 4 cifre. Deschis tuturor.",
      roomCodePlaceholder: "Cod de 4",
      enterRoomBtn: "Intră",
      checkingLogin: "Se verifică autentificarea…",
      loginHint: "Meciul rapid cere Google. La prieteni ajunge codul.",
      matching: "Căutare",
      searched: "Căutare: {time}",
      finding: "Caut un adversar de nivel apropiat...",
      startingSoon: "Începe imediat",
      cancelMatch: "Anulează",
    },
  ),
  hu: pack(
    {
      title: "Becsületkártya",
      rankPrefix: "Helyezés",
      rankSuffix: "",
      maxStreak: "Legjobb sorozat",
      points: "pont",
      leaderboardBtn: "Ranglista",
      unranked: "Még nincs helyezésed. Indíts kihívást!",
      loading: "Eredmény betöltése…",
      signInHint: "Lépj be, hogy megmaradjon a pont és a hely",
    },
    { title: "Témacsomagok", subtitle: "Hamarosan / Válogatott paklik" },
    {
      badge: "CHALLENGE",
      title: "Kihívás mód",
      rule1: "Kérdésenként csak 10 másodperc.",
      rule2: "A találat 1000 plusz a maradék idő. Gyorsabban több.",
      rule3: "Egy hiba vagy az idő azonnal véget vet a körnek.",
      startBtn: "Kihívás indítása",
      backHome: "Vissza a főoldalra",
    },
    {
      backHome: "Vissza a főoldalra",
      title: "Többjátékos PK",
      subtitle: "Véletlen ellenfél, vagy barátok 4 jegyű kóddal.",
      randomMatchTitle: "Gyors meccs (1v1)",
      randomMatchDesc: "Online játékosokat keres. 2 főnél indul.",
      vipPrivilege: "VIP házigazda",
      createRoomTitle: "Privát szoba létrehozása",
      createRoomDesc: "A privát szoba csak VIP-nek jár.",
      createRoomReady: "4 jegyű kód. A házigazda 2–4 játékossal indít.",
      checkingHost: "Jogosultság ellenőrzése…",
      creatingCode: "Kód készítése…",
      joinRoomTitle: "Belépés a szobába",
      joinRoomDesc: "Írd be a helyes 4 jegyű kódot. Mindenkinek nyitva.",
      roomCodePlaceholder: "4 jegyű kód",
      enterRoomBtn: "Belépés",
      checkingLogin: "Bejelentkezés ellenőrzése…",
      loginHint: "A gyors meccshez Google kell. Barátokhoz elég a kód.",
      matching: "Keresés",
      searched: "Keresés: {time}",
      finding: "Hasonló ellenfelet keresek...",
      startingSoon: "Mindjárt indul",
      cancelMatch: "Mégse",
    },
  ),
  he: pack(
    {
      title: "כרטיס כבוד",
      rankPrefix: "מקום",
      rankSuffix: "",
      maxStreak: "הרצף הטוב",
      points: "נק׳",
      leaderboardBtn: "טבלה",
      unranked: "עדיין בלי דירוג. התחילו אתגר!",
      loading: "טוען את השיא…",
      signInHint: "התחברו כדי לשמור ניקוד ומקום",
    },
    { title: "חבילות נושא", subtitle: "בקרוב / חפיסות נבחרות" },
    {
      badge: "CHALLENGE",
      title: "מצב אתגר",
      rule1: "רק 10 שניות לכל שאלה.",
      rule2: "תשובה נכונה שווה 1000 ועוד בונוס זמן. מהר יותר, גבוה יותר.",
      rule3: "טעות אחת או סיום הזמן מסיימים את הסיבוב מיד.",
      startBtn: "התחלת אתגר",
      backHome: "חזרה הביתה",
    },
    {
      backHome: "חזרה הביתה",
      title: "PK מרובה משתתפים",
      subtitle: "יריב אקראי, או חברים עם קוד בן 4 ספרות.",
      randomMatchTitle: "התאמה מהירה (1v1)",
      randomMatchDesc: "מחפש שחקנים אונליין. מתחילים ב-2.",
      vipPrivilege: "מארח VIP",
      createRoomTitle: "יצירת חדר פרטי",
      createRoomDesc: "חדרים פרטיים רק ל-VIP.",
      createRoomReady: "קוד בן 4 ספרות. המארח מתחיל עם 2–4 שחקנים.",
      checkingHost: "בודק הרשאה…",
      creatingCode: "יוצר קוד…",
      joinRoomTitle: "הצטרפות לחדר",
      joinRoomDesc: "הזינו קוד נכון בן 4 ספרות. פתוח לכולם.",
      roomCodePlaceholder: "קוד בן 4",
      enterRoomBtn: "כניסה",
      checkingLogin: "בודק התחברות…",
      loginHint: "להתאמה מהירה צריך Google. לחברים מספיק הקוד.",
      matching: "חיפוש",
      searched: "חיפוש: {time}",
      finding: "מחפש יריב ברמה קרובה...",
      startingSoon: "מתחיל עוד רגע",
      cancelMatch: "ביטול",
    },
  ),
  ms: pack(
    {
      title: "Kad kehormatan",
      rankPrefix: "Kedudukan",
      rankSuffix: "",
      maxStreak: "Rentetan terbaik",
      points: "mata",
      leaderboardBtn: "Carta",
      unranked: "Belum ada kedudukan. Mulakan cabaran!",
      loading: "Memuatkan rekod…",
      signInHint: "Log masuk untuk simpan mata dan kedudukan",
    },
    { title: "Pek tema", subtitle: "Akan datang / Dek pilihan" },
    {
      badge: "CHALLENGE",
      title: "Mod cabaran",
      rule1: "Hanya 10 saat setiap soalan.",
      rule2: "Betul dapat 1000 tambah baki masa. Lebih laju, lebih tinggi.",
      rule3: "Satu salah atau masa habis terus tamatkan pusingan.",
      startBtn: "Mula cabaran",
      backHome: "Kembali ke laman utama",
    },
    {
      backHome: "Kembali ke laman utama",
      title: "PK ramai pemain",
      subtitle: "Lawan rawak, atau kawan dengan kod 4 digit.",
      randomMatchTitle: "Padanan pantas (1v1)",
      randomMatchDesc: "Cari pemain dalam talian. Mula apabila ada 2 orang.",
      vipPrivilege: "Hos VIP",
      createRoomTitle: "Cipta bilik peribadi",
      createRoomDesc: "Bilik peribadi hanya untuk VIP.",
      createRoomReady: "Kod 4 digit. Hos mula dengan 2–4 pemain.",
      checkingHost: "Menyemak kebenaran…",
      creatingCode: "Menjana kod…",
      joinRoomTitle: "Masuk bilik",
      joinRoomDesc: "Masukkan kod 4 digit yang betul. Terbuka untuk semua.",
      roomCodePlaceholder: "Kod 4 digit",
      enterRoomBtn: "Masuk",
      checkingLogin: "Menyemak log masuk…",
      loginHint: "Padanan pantas perlukan Google. Bilik kawan cukup dengan kod.",
      matching: "Mencari",
      searched: "Mencari: {time}",
      finding: "Mencari lawan yang setara...",
      startingSoon: "Hampir mula",
      cancelMatch: "Batal",
    },
  ),
  fa: pack(
    {
      title: "کارت افتخار",
      rankPrefix: "رتبه",
      rankSuffix: "",
      maxStreak: "بهترین برد پیاپی",
      points: "امتیاز",
      leaderboardBtn: "جدول",
      unranked: "هنوز رتبه‌ای نداری. چالش را شروع کن!",
      loading: "در حال بارگذاری رکورد…",
      signInHint: "برای ذخیره امتیاز و رتبه وارد شو",
    },
    { title: "بسته‌های موضوعی", subtitle: "به‌زودی / دسته‌های برگزیده" },
    {
      badge: "CHALLENGE",
      title: "حالت چالش",
      rule1: "هر سؤال فقط ۱۰ ثانیه.",
      rule2: "جواب درست ۱۰۰۰ به‌علاوه زمان باقی‌مانده. سریع‌تر، بالاتر.",
      rule3: "یک غلط یا پایان زمان، این دور را فوراً تمام می‌کند.",
      startBtn: "شروع چالش",
      backHome: "بازگشت به خانه",
    },
    {
      backHome: "بازگشت به خانه",
      title: "PK چندنفره",
      subtitle: "حریف تصادفی، یا دوستان با کد ۴ رقمی.",
      randomMatchTitle: "مسابقه سریع (1v1)",
      randomMatchDesc: "بازیکن آنلاین در جهان را پیدا کن. با ۲ نفر شروع می‌شود.",
      vipPrivilege: "میزبان ویژه VIP",
      createRoomTitle: "ساخت اتاق خصوصی",
      createRoomDesc: "اتاق خصوصی فقط برای VIP است.",
      createRoomReady: "کد ۴ رقمی. میزبان با ۲ تا ۴ نفر شروع می‌کند.",
      checkingHost: "در حال بررسی مجوز…",
      creatingCode: "در حال ساخت کد…",
      joinRoomTitle: "ورود به اتاق",
      joinRoomDesc: "کد درست ۴ رقمی را وارد کن. برای همه باز است.",
      roomCodePlaceholder: "کد ۴ رقمی",
      enterRoomBtn: "ورود",
      checkingLogin: "در حال بررسی ورود…",
      loginHint: "مسابقه سریع به ورود Google نیاز دارد. اتاق دوستان فقط کد می‌خواهد.",
      matching: "جستجو",
      searched: "جستجو: {time}",
      finding: "در حال پیدا کردن حریف هم‌سطح...",
      startingSoon: "به‌زودی شروع",
      cancelMatch: "لغو",
    },
  ),
  fil: pack(
    {
      title: "Honor card",
      rankPrefix: "Ranggo",
      rankSuffix: "",
      maxStreak: "Pinakamahabang sunod",
      points: "puntos",
      leaderboardBtn: "Leaderboard",
      unranked: "Wala ka pa sa ranggo. Magsimula ng challenge!",
      loading: "Niloload ang rekord…",
      signInHint: "Mag-log in para masave ang puntos at ranggo",
    },
    { title: "Mga theme pack", subtitle: "Malapit na / Piniling deck" },
    {
      badge: "CHALLENGE",
      title: "Challenge mode",
      rule1: "10 segundo lang bawat tanong.",
      rule2: "Tama ay 1000 dagdag ang natitirang oras. Mas mabilis, mas mataas.",
      rule3: "Isang mali o timeout, tapos agad ang round.",
      startBtn: "Simulan ang challenge",
      backHome: "Bumalik sa home",
    },
    {
      backHome: "Bumalik sa home",
      title: "Multiplayer PK",
      subtitle: "Random na kalaban, o kaibigan gamit ang 4-digit na code.",
      randomMatchTitle: "Quick match (1v1)",
      randomMatchDesc: "Humanap ng online players. Magsisimula sa 2 tao.",
      vipPrivilege: "VIP host lang",
      createRoomTitle: "Gumawa ng private room",
      createRoomDesc: "Private room para lang sa VIP.",
      createRoomReady: "4-digit na code. Sisimulan ng host kapag 2–4 na tao.",
      checkingHost: "Tinitingnan ang permiso…",
      creatingCode: "Ginagawa ang code…",
      joinRoomTitle: "Sumali sa room",
      joinRoomDesc: "Ilagay ang tamang 4-digit na code. Bukas sa lahat.",
      roomCodePlaceholder: "4-digit na code",
      enterRoomBtn: "Pumasok",
      checkingLogin: "Tinitingnan ang login…",
      loginHint: "Kailangan ng Google para sa quick match. Sa kaibigan, code lang.",
      matching: "Naghahanap",
      searched: "Naghahanap: {time}",
      finding: "Naghahanap ng kapantay na kalaban...",
      startingSoon: "Magsisimula na",
      cancelMatch: "Kanselahin",
    },
  ),
  da: pack(
    {
      title: "Æreskort",
      rankPrefix: "Plads",
      rankSuffix: "",
      maxStreak: "Bedste stime",
      points: "point",
      leaderboardBtn: "Rangliste",
      unranked: "Ikke rangeret endnu. Start en udfordring!",
      loading: "Indlæser rekord…",
      signInHint: "Log ind for at gemme point og plads",
    },
    { title: "Temapakker", subtitle: "Kommer snart / Udvalgte sæt" },
    {
      badge: "CHALLENGE",
      title: "Udfordring",
      rule1: "Kun 10 sekunder pr. spørgsmål.",
      rule2: "Rigtigt giver 1000 plus resttid. Hurtigere er højere.",
      rule3: "Én fejl eller tiden slutter runden med det samme.",
      startBtn: "Start udfordring",
      backHome: "Tilbage til forsiden",
    },
    {
      backHome: "Tilbage til forsiden",
      title: "PK med flere",
      subtitle: "En tilfældig modstander, eller venner med en 4-cifret kode.",
      randomMatchTitle: "Hurtig kamp (1v1)",
      randomMatchDesc: "Finder online spillere. Starter ved 2 personer.",
      vipPrivilege: "VIP-vært",
      createRoomTitle: "Opret privat rum",
      createRoomDesc: "Private rum er kun for VIP.",
      createRoomReady: "4-cifret kode. Værten starter med 2–4 spillere.",
      checkingHost: "Tjekker adgang…",
      creatingCode: "Opretter kode…",
      joinRoomTitle: "Deltag i rum",
      joinRoomDesc: "Skriv den rigtige 4-cifrede kode. Åbent for alle.",
      roomCodePlaceholder: "4-cifret kode",
      enterRoomBtn: "Gå ind",
      checkingLogin: "Tjekker login…",
      loginHint: "Hurtig kamp kræver Google. Venner behøver kun koden.",
      matching: "Søger",
      searched: "Søger: {time}",
      finding: "Leder efter en jævnbyrdig modstander...",
      startingSoon: "Starter snart",
      cancelMatch: "Annuller",
    },
  ),
  fi: pack(
    {
      title: "Kunniakortti",
      rankPrefix: "Sija",
      rankSuffix: "",
      maxStreak: "Paras putki",
      points: "pst",
      leaderboardBtn: "Tulostaulu",
      unranked: "Ei vielä sijoitusta. Aloita haaste!",
      loading: "Ladataan ennätystä…",
      signInHint: "Kirjaudu, jotta pisteet ja sija säilyvät",
    },
    { title: "Teemapaketit", subtitle: "Tulossa / Valitut pakat" },
    {
      badge: "CHALLENGE",
      title: "Haastetila",
      rule1: "Vain 10 sekuntia kysymystä kohti.",
      rule2: "Oikea vastaus on 1000 plus jäljellä oleva aika. Nopeammin on enemmän.",
      rule3: "Yksi virhe tai aika päättää kierroksen heti.",
      startBtn: "Aloita haaste",
      backHome: "Takaisin kotiin",
    },
    {
      backHome: "Takaisin kotiin",
      title: "Moninpeli-PK",
      subtitle: "Satunnainen vastustaja tai kaverit 4-numeroisella koodilla.",
      randomMatchTitle: "Pikamatsi (1v1)",
      randomMatchDesc: "Etsii pelaajia verkosta. Alkaa kahdella pelaajalla.",
      vipPrivilege: "VIP-isäntä",
      createRoomTitle: "Luo yksityishuone",
      createRoomDesc: "Yksityishuoneet ovat vain VIP-pelaajille.",
      createRoomReady: "4-numeroinen koodi. Isäntä aloittaa 2–4 pelaajalla.",
      checkingHost: "Tarkistetaan oikeutta…",
      creatingCode: "Luodaan koodia…",
      joinRoomTitle: "Liity huoneeseen",
      joinRoomDesc: "Syötä oikea 4-numeroinen koodi. Avoin kaikille.",
      roomCodePlaceholder: "4-numeroinen koodi",
      enterRoomBtn: "Sisään",
      checkingLogin: "Tarkistetaan kirjautumista…",
      loginHint: "Pikamatsi vaatii Googlen. Kavereille riittää koodi.",
      matching: "Etsitään",
      searched: "Etsitään: {time}",
      finding: "Etsitään tasaväkistä vastustajaa...",
      startingSoon: "Alkaa kohta",
      cancelMatch: "Peruuta",
    },
  ),
};

export function sectionsFor(language: LanguageCode): UiSections {
  return UI_SECTIONS[language] ?? UI_SECTIONS.en;
}

export function fillTemplate(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, name: string) => {
    const value = vars[name];
    return value === undefined ? match : String(value);
  });
}
