import type { LanguageCode } from "@/lib/languages";

export type VipModalCopy = {
  title: string;
  subtitle: string;
  privilege1Title: string;
  privilege1Desc: string;
  privilege2Title: string;
  privilege2Desc: string;
  privilege3Title: string;
  privilege3Desc: string;
  privilege4Title: string;
  privilege4Desc: string;
  promoBadge: string;
  planATitle: string;
  planABadge: string;
  planAPrice: string;
  planBTitle: string;
  planBPrice: string;
  planBDesc: string;
  payBtn: string;
  closeBtn: string;
  testToggle: string;
  testBusy: string;
};

const VIP_COPY: Record<LanguageCode, VipModalCopy> = {
  "zh-TW": {
    title: "👑 升級 VIP 尊榮會員",
    subtitle: "解鎖好友房間隨時開黑，享受全站純淨零廣告！",
    privilege1Title: "自建好友房",
    privilege1Desc: "支援 2~4 人私人房間開黑連線",
    privilege2Title: "全站無廣告",
    privilege2Desc: "經典 15 題與挑戰 3 局廣告永久豁免",
    privilege3Title: "尊爵榮譽",
    privilege3Desc: "天梯榜與個人榮譽卡獨家金色微光認證",
    privilege4Title: "優先曝光",
    privilege4Desc: "你出的題目自動獲推薦優先展示",
    promoBadge: "驗證期特惠",
    planATitle: "方案 A · 推薦",
    planABadge: "限時嘗鮮價",
    planAPrice: "NT$ 19 / 月",
    planBTitle: "方案 B",
    planBPrice: "NT$ 39",
    planBDesc: "一次性終身買斷（永久去廣告，解鎖所有功能）",
    payBtn: "💳 前往付款開通特權",
    closeBtn: "先不用，我知道了",
    testToggle: "🛠️ 本機測試模式：一鍵切換 VIP",
    testBusy: "正在切換…",
  },
  "zh-CN": {
    title: "👑 升级 VIP 尊荣会员",
    subtitle: "解锁好友房间随时开黑，享受全站纯净零广告！",
    privilege1Title: "自建好友房",
    privilege1Desc: "支持 2~4 人私人房间开黑连线",
    privilege2Title: "全站无广告",
    privilege2Desc: "经典 15 题与挑战 3 局广告永久豁免",
    privilege3Title: "尊爵荣誉",
    privilege3Desc: "天梯榜与个人荣誉卡独家金色微光认证",
    privilege4Title: "优先曝光",
    privilege4Desc: "你出的题目自动获推荐优先展示",
    promoBadge: "验证期特惠",
    planATitle: "方案 A · 推荐",
    planABadge: "限时尝鲜价",
    planAPrice: "NT$ 19 / 月",
    planBTitle: "方案 B",
    planBPrice: "NT$ 39",
    planBDesc: "一次性终身买断（永久去广告，解锁所有功能）",
    payBtn: "💳 前往付款开通特权",
    closeBtn: "先不用，我知道了",
    testToggle: "🛠️ 本机测试模式：一键切换 VIP",
    testBusy: "正在切换…",
  },
  en: {
    title: "👑 Upgrade to VIP",
    subtitle: "Unlock private rooms to play with friends & enjoy zero ads!",
    privilege1Title: "Host Private Rooms",
    privilege1Desc: "Host 2-4 player custom private rooms",
    privilege2Title: "Ad-Free Experience",
    privilege2Desc: "Zero ads across casual and challenge runs",
    privilege3Title: "Exclusive Honor",
    privilege3Desc: "Golden badge on leaderboards & profile",
    privilege4Title: "Priority Exposure",
    privilege4Desc: "Your submitted quizzes get featured first",
    promoBadge: "Special Offer",
    planATitle: "Plan A · Popular",
    planABadge: "Limited Time",
    planAPrice: "NT$ 19 / mo",
    planBTitle: "Plan B",
    planBPrice: "NT$ 39",
    planBDesc: "Lifetime purchase (Permanent ad-free, unlock all features)",
    payBtn: "💳 Proceed to Checkout",
    closeBtn: "Maybe later, I got it",
    testToggle: "🛠️ Dev Mode: Toggle VIP",
    testBusy: "Switching…",
  },
  es: {
    title: "👑 Mejora a VIP",
    subtitle: "Desbloquea salas privadas para jugar con amigos y cero anuncios.",
    privilege1Title: "Salas privadas",
    privilege1Desc: "Crea salas privadas de 2 a 4 jugadores",
    privilege2Title: "Sin anuncios",
    privilege2Desc: "Cero anuncios en partidas clásicas y de desafío",
    privilege3Title: "Honor exclusivo",
    privilege3Desc: "Insignia dorada en la clasificación y el perfil",
    privilege4Title: "Exposición prioritaria",
    privilege4Desc: "Tus preguntas aparecen primero",
    promoBadge: "Oferta especial",
    planATitle: "Plan A · Popular",
    planABadge: "Tiempo limitado",
    planAPrice: "NT$ 19 / mes",
    planBTitle: "Plan B",
    planBPrice: "NT$ 39",
    planBDesc: "Compra de por vida (sin anuncios para siempre y todas las funciones)",
    payBtn: "💳 Ir al pago",
    closeBtn: "Ahora no, entendido",
    testToggle: "🛠️ Modo local: alternar VIP",
    testBusy: "Cambiando…",
  },
  ja: {
    title: "👑 VIPにアップグレード",
    subtitle: "フレンド部屋を解放して、サイト全体の広告をなくそう！",
    privilege1Title: "フレンド部屋",
    privilege1Desc: "2〜4人のプライベート部屋で対戦",
    privilege2Title: "広告なし",
    privilege2Desc: "通常15問とチャレンジの広告を永久免除",
    privilege3Title: "限定栄誉",
    privilege3Desc: "ランキングと栄誉カードに金色の認証",
    privilege4Title: "優先表示",
    privilege4Desc: "投稿した問題が優先的に掲載されます",
    promoBadge: "特別価格",
    planATitle: "プラン A · おすすめ",
    planABadge: "期間限定",
    planAPrice: "NT$ 19 / 月",
    planBTitle: "プラン B",
    planBPrice: "NT$ 39",
    planBDesc: "買い切り（広告なし永久、全機能を解放）",
    payBtn: "💳 支払って特典を開通",
    closeBtn: "あとで、了解",
    testToggle: "🛠️ ローカルテスト：VIPを切り替え",
    testBusy: "切り替え中…",
  },
  ko: {
    title: "👑 VIP로 업그레이드",
    subtitle: "친구 방을 열고, 사이트 전체 광고 없이 즐기세요!",
    privilege1Title: "친구 방 만들기",
    privilege1Desc: "2~4인 비공개 방으로 함께 플레이",
    privilege2Title: "광고 없음",
    privilege2Desc: "클래식과 챌린지 광고를 영구 면제",
    privilege3Title: "전용 명예",
    privilege3Desc: "랭킹과 명예 카드에 골드 인증",
    privilege4Title: "우선 노출",
    privilege4Desc: "내가 낸 문제가 먼저 추천됩니다",
    promoBadge: "특별 혜택",
    planATitle: "플랜 A · 추천",
    planABadge: "한정 특가",
    planAPrice: "NT$ 19 / 월",
    planBTitle: "플랜 B",
    planBPrice: "NT$ 39",
    planBDesc: "평생 일회 구매 (영구 광고 제거, 모든 기능 잠금 해제)",
    payBtn: "💳 결제하고 특권 열기",
    closeBtn: "나중에, 알겠어요",
    testToggle: "🛠️ 로컬 테스트: VIP 전환",
    testBusy: "전환 중…",
  },
  pt: {
    title: "👑 Upgrade para VIP",
    subtitle: "Desbloqueie salas privadas com amigos e zero anúncios!",
    privilege1Title: "Salas privadas",
    privilege1Desc: "Crie salas privadas de 2 a 4 jogadores",
    privilege2Title: "Sem anúncios",
    privilege2Desc: "Zero anúncios no modo clássico e no desafio",
    privilege3Title: "Honra exclusiva",
    privilege3Desc: "Selo dourado no ranking e no perfil",
    privilege4Title: "Destaque prioritário",
    privilege4Desc: "Seus quizzes aparecem primeiro",
    promoBadge: "Oferta especial",
    planATitle: "Plano A · Popular",
    planABadge: "Tempo limitado",
    planAPrice: "NT$ 19 / mês",
    planBTitle: "Plano B",
    planBPrice: "NT$ 39",
    planBDesc: "Compra vitalícia (sem anúncios para sempre e todos os recursos)",
    payBtn: "💳 Ir para o pagamento",
    closeBtn: "Agora não, entendi",
    testToggle: "🛠️ Modo local: alternar VIP",
    testBusy: "Alternando…",
  },
  ru: {
    title: "👑 Перейти на VIP",
    subtitle: "Откройте комнаты для друзей и уберите всю рекламу!",
    privilege1Title: "Свои комнаты",
    privilege1Desc: "Приватные комнаты на 2–4 игроков",
    privilege2Title: "Без рекламы",
    privilege2Desc: "Без рекламы в обычном и челлендж-режиме",
    privilege3Title: "Особая честь",
    privilege3Desc: "Золотой знак в рейтинге и на карточке",
    privilege4Title: "Приоритет",
    privilege4Desc: "Ваши вопросы показываются первыми",
    promoBadge: "Спецпредложение",
    planATitle: "План A · Хит",
    planABadge: "Ограничено",
    planAPrice: "NT$ 19 / мес",
    planBTitle: "План B",
    planBPrice: "NT$ 39",
    planBDesc: "Пожизненная покупка (без рекламы навсегда и все функции)",
    payBtn: "💳 Перейти к оплате",
    closeBtn: "Позже, понятно",
    testToggle: "🛠️ Локальный тест: переключить VIP",
    testBusy: "Переключение…",
  },
  de: {
    title: "👑 VIP werden",
    subtitle: "Private Räume mit Freunden und keine Werbung auf der ganzen Seite!",
    privilege1Title: "Private Räume",
    privilege1Desc: "Private Räume für 2–4 Spieler",
    privilege2Title: "Werbefrei",
    privilege2Desc: "Keine Werbung in Klassik und Challenge",
    privilege3Title: "Exklusive Ehre",
    privilege3Desc: "Goldenes Abzeichen in Rangliste und Profil",
    privilege4Title: "Priorität",
    privilege4Desc: "Deine Fragen werden zuerst gezeigt",
    promoBadge: "Sonderangebot",
    planATitle: "Plan A · Beliebt",
    planABadge: "Nur jetzt",
    planAPrice: "NT$ 19 / Monat",
    planBTitle: "Plan B",
    planBPrice: "NT$ 39",
    planBDesc: "Einmaliger Kauf (dauerhaft werbefrei, alle Funktionen)",
    payBtn: "💳 Zur Zahlung",
    closeBtn: "Später, verstanden",
    testToggle: "🛠️ Lokaltest: VIP umschalten",
    testBusy: "Wird umgeschaltet…",
  },
  fr: {
    title: "👑 Passer VIP",
    subtitle: "Débloquez les salons privés entre amis et zéro pub sur tout le site !",
    privilege1Title: "Salons privés",
    privilege1Desc: "Salons privés de 2 à 4 joueurs",
    privilege2Title: "Sans publicité",
    privilege2Desc: "Zéro pub en mode classique et défi",
    privilege3Title: "Honneur exclusif",
    privilege3Desc: "Badge doré au classement et sur le profil",
    privilege4Title: "Mise en avant",
    privilege4Desc: "Vos questions sont affichées en priorité",
    promoBadge: "Offre spéciale",
    planATitle: "Offre A · Populaire",
    planABadge: "Durée limitée",
    planAPrice: "NT$ 19 / mois",
    planBTitle: "Offre B",
    planBPrice: "NT$ 39",
    planBDesc: "Achat à vie (sans pub pour toujours, toutes les fonctions)",
    payBtn: "💳 Passer au paiement",
    closeBtn: "Plus tard, compris",
    testToggle: "🛠️ Mode local : basculer VIP",
    testBusy: "Changement…",
  },
  ar: {
    title: "👑 الترقية إلى VIP",
    subtitle: "افتح غرف الأصدقاء واستمتع بالموقع بلا إعلانات!",
    privilege1Title: "غرف خاصة",
    privilege1Desc: "غرف خاصة من 2 إلى 4 لاعبين",
    privilege2Title: "بدون إعلانات",
    privilege2Desc: "إعفاء دائم من الإعلانات في الوضع العادي والتحدي",
    privilege3Title: "شرف حصري",
    privilege3Desc: "شارة ذهبية في الترتيب وبطاقة الشرف",
    privilege4Title: "أولوية الظهور",
    privilege4Desc: "أسئلتك تُعرض أولاً",
    promoBadge: "عرض خاص",
    planATitle: "الخطة A · موصى بها",
    planABadge: "لفترة محدودة",
    planAPrice: "NT$ 19 / شهر",
    planBTitle: "الخطة B",
    planBPrice: "NT$ 39",
    planBDesc: "شراء مدى الحياة (بدون إعلانات للأبد وفتح كل الميزات)",
    payBtn: "💳 المتابعة للدفع",
    closeBtn: "لاحقًا، فهمت",
    testToggle: "🛠️ وضع الاختبار: تبديل VIP",
    testBusy: "جارٍ التبديل…",
  },
  hi: {
    title: "👑 VIP में अपग्रेड करें",
    subtitle: "दोस्तों के साथ निजी कमरे खोलें और पूरी साइट पर शून्य विज्ञापन!",
    privilege1Title: "निजी कमरे",
    privilege1Desc: "2–4 खिलाड़ियों के निजी कमरे",
    privilege2Title: "विज्ञापन-मुक्त",
    privilege2Desc: "क्लासिक और चैलेंज में स्थायी रूप से शून्य विज्ञापन",
    privilege3Title: "विशेष सम्मान",
    privilege3Desc: "लीडरबोर्ड और प्रोफ़ाइल पर सुनहरा बैज",
    privilege4Title: "प्राथमिकता",
    privilege4Desc: "आपके प्रश्न पहले दिखाए जाते हैं",
    promoBadge: "विशेष ऑफ़र",
    planATitle: "प्लान A · लोकप्रिय",
    planABadge: "सीमित समय",
    planAPrice: "NT$ 19 / माह",
    planBTitle: "प्लान B",
    planBPrice: "NT$ 39",
    planBDesc: "आजीवन खरीद (स्थायी विज्ञापन-मुक्त, सभी सुविधाएँ)",
    payBtn: "💳 भुगतान करें",
    closeBtn: "बाद में, समझ गया",
    testToggle: "🛠️ लोकल टेस्ट: VIP बदलें",
    testBusy: "बदल रहे हैं…",
  },
  bn: {
    title: "👑 VIP-তে আপগ্রেড",
    subtitle: "বন্ধুদের সঙ্গে ব্যক্তিগত রুম খুলুন, পুরো সাইটে শূন্য বিজ্ঞাপন!",
    privilege1Title: "ব্যক্তিগত রুম",
    privilege1Desc: "২–৪ জনের ব্যক্তিগত রুম",
    privilege2Title: "বিজ্ঞাপনমুক্ত",
    privilege2Desc: "ক্লাসিক ও চ্যালেঞ্জে স্থায়ীভাবে শূন্য বিজ্ঞাপন",
    privilege3Title: "বিশেষ সম্মান",
    privilege3Desc: "লিডারবোর্ড ও প্রোফাইলে সোনালি ব্যাজ",
    privilege4Title: "অগ্রাধিকার",
    privilege4Desc: "আপনার প্রশ্ন আগে দেখানো হয়",
    promoBadge: "বিশেষ অফার",
    planATitle: "প্ল্যান A · জনপ্রিয়",
    planABadge: "সীমিত সময়",
    planAPrice: "NT$ 19 / মাস",
    planBTitle: "প্ল্যান B",
    planBPrice: "NT$ 39",
    planBDesc: "আজীবন ক্রয় (স্থায়ী বিজ্ঞাপনমুক্ত, সব ফিচার)",
    payBtn: "💳 পেমেন্টে যান",
    closeBtn: "পরে, বুঝেছি",
    testToggle: "🛠️ লোকাল টেস্ট: VIP বদলান",
    testBusy: "বদলানো হচ্ছে…",
  },
  id: {
    title: "👑 Upgrade ke VIP",
    subtitle: "Buka ruang teman dan nikmati situs tanpa iklan!",
    privilege1Title: "Ruang pribadi",
    privilege1Desc: "Ruang pribadi untuk 2–4 pemain",
    privilege2Title: "Bebas iklan",
    privilege2Desc: "Tanpa iklan selamanya di mode klasik dan tantangan",
    privilege3Title: "Kehormatan eksklusif",
    privilege3Desc: "Lencana emas di papan peringkat dan profil",
    privilege4Title: "Prioritas tampil",
    privilege4Desc: "Kuis yang kamu buat ditampilkan lebih dulu",
    promoBadge: "Penawaran khusus",
    planATitle: "Paket A · Populer",
    planABadge: "Waktu terbatas",
    planAPrice: "NT$ 19 / bln",
    planBTitle: "Paket B",
    planBPrice: "NT$ 39",
    planBDesc: "Beli seumur hidup (bebas iklan permanen, buka semua fitur)",
    payBtn: "💳 Lanjut ke pembayaran",
    closeBtn: "Nanti saja, mengerti",
    testToggle: "🛠️ Mode lokal: alihkan VIP",
    testBusy: "Mengalihkan…",
  },
  it: {
    title: "👑 Passa a VIP",
    subtitle: "Sblocca le stanze private con gli amici e zero pubblicità!",
    privilege1Title: "Stanze private",
    privilege1Desc: "Stanze private da 2 a 4 giocatori",
    privilege2Title: "Senza pubblicità",
    privilege2Desc: "Zero pubblicità in classica e sfida, per sempre",
    privilege3Title: "Onore esclusivo",
    privilege3Desc: "Badge dorato in classifica e sul profilo",
    privilege4Title: "Priorità",
    privilege4Desc: "I tuoi quiz vengono mostrati per primi",
    promoBadge: "Offerta speciale",
    planATitle: "Piano A · Popolare",
    planABadge: "Tempo limitato",
    planAPrice: "NT$ 19 / mese",
    planBTitle: "Piano B",
    planBPrice: "NT$ 39",
    planBDesc: "Acquisto a vita (niente pubblicità per sempre, tutte le funzioni)",
    payBtn: "💳 Vai al pagamento",
    closeBtn: "Più tardi, capito",
    testToggle: "🛠️ Modalità locale: cambia VIP",
    testBusy: "Cambio in corso…",
  },
  th: {
    title: "👑 อัปเกรดเป็น VIP",
    subtitle: "ปลดล็อกห้องเพื่อนและเล่นทั้งเว็บแบบไม่มีโฆษณา!",
    privilege1Title: "ห้องส่วนตัว",
    privilege1Desc: "ห้องส่วนตัว 2–4 คน",
    privilege2Title: "ไม่มีโฆษณา",
    privilege2Desc: "ไม่มีโฆษณาถาวรทั้งโหมดปกติและชาเลนจ์",
    privilege3Title: "เกียรติพิเศษ",
    privilege3Desc: "ตราทองบนกระดานอันดับและโปรไฟล์",
    privilege4Title: "แสดงก่อน",
    privilege4Desc: "คำถามที่คุณส่งจะถูกแนะนำก่อน",
    promoBadge: "ข้อเสนอพิเศษ",
    planATitle: "แผน A · แนะนำ",
    planABadge: "เวลาจำกัด",
    planAPrice: "NT$ 19 / เดือน",
    planBTitle: "แผน B",
    planBPrice: "NT$ 39",
    planBDesc: "ซื้อขาดตลอดชีพ (ไม่มีโฆษณาถาวร ปลดล็อกทุกฟีเจอร์)",
    payBtn: "💳 ไปชำระเงิน",
    closeBtn: "ไว้ก่อน เข้าใจแล้ว",
    testToggle: "🛠️ โหมดทดสอบ: สลับ VIP",
    testBusy: "กำลังสลับ…",
  },
  pl: {
    title: "👑 Przejdź na VIP",
    subtitle: "Odblokuj pokoje ze znajomymi i zero reklam na całej stronie!",
    privilege1Title: "Prywatne pokoje",
    privilege1Desc: "Prywatne pokoje dla 2–4 graczy",
    privilege2Title: "Bez reklam",
    privilege2Desc: "Zero reklam na stałe w trybie klasycznym i wyzwaniu",
    privilege3Title: "Wyjątkowy honor",
    privilege3Desc: "Złota odznaka w rankingu i na profilu",
    privilege4Title: "Priorytet",
    privilege4Desc: "Twoje pytania są pokazywane pierwsze",
    promoBadge: "Oferta specjalna",
    planATitle: "Plan A · Popularny",
    planABadge: "Ograniczony czas",
    planAPrice: "NT$ 19 / mies.",
    planBTitle: "Plan B",
    planBPrice: "NT$ 39",
    planBDesc: "Zakup na zawsze (bez reklam na stałe i wszystkie funkcje)",
    payBtn: "💳 Przejdź do płatności",
    closeBtn: "Później, rozumiem",
    testToggle: "🛠️ Tryb lokalny: przełącz VIP",
    testBusy: "Przełączanie…",
  },
  uk: {
    title: "👑 Перейти на VIP",
    subtitle: "Відкрийте кімнати для друзів і приберіть усю рекламу!",
    privilege1Title: "Приватні кімнати",
    privilege1Desc: "Приватні кімнати на 2–4 гравців",
    privilege2Title: "Без реклами",
    privilege2Desc: "Без реклами назавжди в класиці та челенджі",
    privilege3Title: "Особлива честь",
    privilege3Desc: "Золотий знак у рейтингу та на профілі",
    privilege4Title: "Пріоритет",
    privilege4Desc: "Ваші запитання показуються першими",
    promoBadge: "Спецпропозиція",
    planATitle: "План A · Популярний",
    planABadge: "Обмежений час",
    planAPrice: "NT$ 19 / міс",
    planBTitle: "План B",
    planBPrice: "NT$ 39",
    planBDesc: "Довічна покупка (без реклами назавжди й усі функції)",
    payBtn: "💳 Перейти до оплати",
    closeBtn: "Пізніше, зрозуміло",
    testToggle: "🛠️ Локальний тест: перемкнути VIP",
    testBusy: "Перемикання…",
  },
  nl: {
    title: "👑 Upgrade naar VIP",
    subtitle: "Ontgrendel vriendenkamers en geniet van nul advertenties!",
    privilege1Title: "Privékamers",
    privilege1Desc: "Privékamers voor 2–4 spelers",
    privilege2Title: "Zonder advertenties",
    privilege2Desc: "Permanent geen advertenties in klassiek en challenge",
    privilege3Title: "Exclusieve eer",
    privilege3Desc: "Gouden badge op de ranglijst en het profiel",
    privilege4Title: "Voorrang",
    privilege4Desc: "Jouw vragen worden als eerste getoond",
    promoBadge: "Speciale aanbieding",
    planATitle: "Plan A · Populair",
    planABadge: "Beperkte tijd",
    planAPrice: "NT$ 19 / mnd",
    planBTitle: "Plan B",
    planBPrice: "NT$ 39",
    planBDesc: "Eenmalige aankoop voor altijd (permanent advertentievrij, alle functies)",
    payBtn: "💳 Naar betalen",
    closeBtn: "Later, begrepen",
    testToggle: "🛠️ Lokale test: VIP wisselen",
    testBusy: "Wisselen…",
  },
  el: {
    title: "👑 Αναβάθμιση σε VIP",
    subtitle: "Ξεκλείδωσε ιδιωτικά δωμάτια με φίλους και μηδέν διαφημίσεις!",
    privilege1Title: "Ιδιωτικά δωμάτια",
    privilege1Desc: "Ιδιωτικά δωμάτια για 2–4 παίκτες",
    privilege2Title: "Χωρίς διαφημίσεις",
    privilege2Desc: "Μηδέν διαφημίσεις για πάντα σε κλασικό και πρόκληση",
    privilege3Title: "Αποκλειστική τιμή",
    privilege3Desc: "Χρυσό σήμα στην κατάταξη και στο προφίλ",
    privilege4Title: "Προτεραιότητα",
    privilege4Desc: "Οι ερωτήσεις σου εμφανίζονται πρώτες",
    promoBadge: "Ειδική προσφορά",
    planATitle: "Πλάνο A · Δημοφιλές",
    planABadge: "Περιορισμένος χρόνος",
    planAPrice: "NT$ 19 / μήνα",
    planBTitle: "Πλάνο B",
    planBPrice: "NT$ 39",
    planBDesc: "Αγορά εφ' όρου ζωής (μόνιμα χωρίς διαφημίσεις, όλες οι λειτουργίες)",
    payBtn: "💳 Μετάβαση στην πληρωμή",
    closeBtn: "Αργότερα, κατάλαβα",
    testToggle: "🛠️ Τοπική δοκιμή: εναλλαγή VIP",
    testBusy: "Εναλλαγή…",
  },
  cs: {
    title: "👑 Přejít na VIP",
    subtitle: "Odemkni místnosti s přáteli a nulové reklamy na celém webu!",
    privilege1Title: "Soukromé místnosti",
    privilege1Desc: "Soukromé místnosti pro 2–4 hráče",
    privilege2Title: "Bez reklam",
    privilege2Desc: "Trvale žádné reklamy v klasice ani výzvě",
    privilege3Title: "Výhradní čest",
    privilege3Desc: "Zlatý odznak v žebříčku a na profilu",
    privilege4Title: "Přednost",
    privilege4Desc: "Tvé otázky se zobrazí jako první",
    promoBadge: "Speciální nabídka",
    planATitle: "Plán A · Oblíbený",
    planABadge: "Omezený čas",
    planAPrice: "NT$ 19 / měs.",
    planBTitle: "Plán B",
    planBPrice: "NT$ 39",
    planBDesc: "Doživotní nákup (trvale bez reklam a všechny funkce)",
    payBtn: "💳 Přejít k platbě",
    closeBtn: "Později, rozumím",
    testToggle: "🛠️ Místní test: přepnout VIP",
    testBusy: "Přepínání…",
  },
  sv: {
    title: "👑 Uppgradera till VIP",
    subtitle: "Lås upp rum med vänner och noll annonser på hela sajten!",
    privilege1Title: "Privata rum",
    privilege1Desc: "Privata rum för 2–4 spelare",
    privilege2Title: "Utan annonser",
    privilege2Desc: "Inga annonser för alltid i klassiskt läge och utmaning",
    privilege3Title: "Exklusiv ära",
    privilege3Desc: "Guldmärke på topplistan och profilen",
    privilege4Title: "Prioritet",
    privilege4Desc: "Dina frågor visas först",
    promoBadge: "Specialerbjudande",
    planATitle: "Plan A · Populär",
    planABadge: "Begränsad tid",
    planAPrice: "NT$ 19 / mån",
    planBTitle: "Plan B",
    planBPrice: "NT$ 39",
    planBDesc: "Livstidsköp (permanent reklamfritt och alla funktioner)",
    payBtn: "💳 Gå till betalning",
    closeBtn: "Senare, jag förstår",
    testToggle: "🛠️ Lokalt test: växla VIP",
    testBusy: "Växlar…",
  },
  ro: {
    title: "👑 Treci la VIP",
    subtitle: "Deblochează camere cu prietenii și zero reclame pe tot site-ul!",
    privilege1Title: "Camere private",
    privilege1Desc: "Camere private pentru 2–4 jucători",
    privilege2Title: "Fără reclame",
    privilege2Desc: "Zero reclame permanent în clasic și provocare",
    privilege3Title: "Onoare exclusivă",
    privilege3Desc: "Insignă aurie în clasament și pe profil",
    privilege4Title: "Prioritate",
    privilege4Desc: "Întrebările tale apar primele",
    promoBadge: "Ofertă specială",
    planATitle: "Planul A · Popular",
    planABadge: "Timp limitat",
    planAPrice: "NT$ 19 / lună",
    planBTitle: "Planul B",
    planBPrice: "NT$ 39",
    planBDesc: "Cumpărare pe viață (fără reclame permanent și toate funcțiile)",
    payBtn: "💳 Mergi la plată",
    closeBtn: "Mai târziu, am înțeles",
    testToggle: "🛠️ Mod local: comută VIP",
    testBusy: "Se comută…",
  },
  hu: {
    title: "👑 Válts VIP-re",
    subtitle: "Nyisd meg a baráti szobákat, és élvezd a reklámmentes oldalt!",
    privilege1Title: "Privát szobák",
    privilege1Desc: "Privát szobák 2–4 játékosnak",
    privilege2Title: "Reklám nélkül",
    privilege2Desc: "Végleg nincs reklám a klasszikus és a kihívás módban",
    privilege3Title: "Különleges becsület",
    privilege3Desc: "Arany jelvény a ranglistán és a profilon",
    privilege4Title: "Elsőbbség",
    privilege4Desc: "A kérdéseid jelennek meg először",
    promoBadge: "Különleges ajánlat",
    planATitle: "A csomag · Népszerű",
    planABadge: "Korlátozott ideig",
    planAPrice: "NT$ 19 / hó",
    planBTitle: "B csomag",
    planBPrice: "NT$ 39",
    planBDesc: "Egyszeri örökös vásárlás (végleg reklám nélkül, minden funkció)",
    payBtn: "💳 Tovább a fizetéshez",
    closeBtn: "Később, értem",
    testToggle: "🛠️ Helyi teszt: VIP váltása",
    testBusy: "Váltás…",
  },
  he: {
    title: "👑 שדרוג ל-VIP",
    subtitle: "פתחו חדרי חברים ותיהנו מאתר בלי פרסומות!",
    privilege1Title: "חדרים פרטיים",
    privilege1Desc: "חדרים פרטיים ל-2–4 שחקנים",
    privilege2Title: "בלי פרסומות",
    privilege2Desc: "אפס פרסומות לתמיד במצב רגיל ובאתגר",
    privilege3Title: "כבוד בלעדי",
    privilege3Desc: "תג זהב בטבלה ובפרופיל",
    privilege4Title: "חשיפה מועדפת",
    privilege4Desc: "השאלות שלכם מוצגות קודם",
    promoBadge: "מבצע מיוחד",
    planATitle: "מסלול A · מומלץ",
    planABadge: "לזמן מוגבל",
    planAPrice: "NT$ 19 / חודש",
    planBTitle: "מסלול B",
    planBPrice: "NT$ 39",
    planBDesc: "רכישה לכל החיים (בלי פרסומות לתמיד וכל התכונות)",
    payBtn: "💳 המשך לתשלום",
    closeBtn: "אחר כך, הבנתי",
    testToggle: "🛠️ מצב בדיקה: החלפת VIP",
    testBusy: "מחליף…",
  },
  ms: {
    title: "👑 Naik taraf ke VIP",
    subtitle: "Buka bilik rakan dan nikmati laman tanpa iklan!",
    privilege1Title: "Bilik peribadi",
    privilege1Desc: "Bilik peribadi untuk 2–4 pemain",
    privilege2Title: "Tanpa iklan",
    privilege2Desc: "Tiada iklan selama-lamanya dalam mod klasik dan cabaran",
    privilege3Title: "Kehormatan eksklusif",
    privilege3Desc: "Lencana emas pada papan kedudukan dan profil",
    privilege4Title: "Keutamaan",
    privilege4Desc: "Kuiz anda dipaparkan dahulu",
    promoBadge: "Tawaran khas",
    planATitle: "Pelan A · Popular",
    planABadge: "Masa terhad",
    planAPrice: "NT$ 19 / bln",
    planBTitle: "Pelan B",
    planBPrice: "NT$ 39",
    planBDesc: "Beli seumur hidup (tanpa iklan kekal, buka semua ciri)",
    payBtn: "💳 Terus ke pembayaran",
    closeBtn: "Nanti, faham",
    testToggle: "🛠️ Mod tempatan: togol VIP",
    testBusy: "Menukar…",
  },
  fa: {
    title: "👑 ارتقا به VIP",
    subtitle: "اتاق دوستان را باز کنید و از سایت بدون تبلیغ لذت ببرید!",
    privilege1Title: "اتاق خصوصی",
    privilege1Desc: "اتاق خصوصی برای ۲ تا ۴ بازیکن",
    privilege2Title: "بدون تبلیغ",
    privilege2Desc: "حذف دائمی تبلیغ در حالت عادی و چالش",
    privilege3Title: "افتخار ویژه",
    privilege3Desc: "نشان طلایی در جدول و نمایه",
    privilege4Title: "نمایش اولویت‌دار",
    privilege4Desc: "سؤال‌های شما اول نمایش داده می‌شوند",
    promoBadge: "پیشنهاد ویژه",
    planATitle: "طرح A · محبوب",
    planABadge: "زمان محدود",
    planAPrice: "NT$ 19 / ماه",
    planBTitle: "طرح B",
    planBPrice: "NT$ 39",
    planBDesc: "خرید مادام‌العمر (بدون تبلیغ برای همیشه و باز شدن همه قابلیت‌ها)",
    payBtn: "💳 ادامه به پرداخت",
    closeBtn: "بعداً، فهمیدم",
    testToggle: "🛠️ حالت آزمایش: تغییر VIP",
    testBusy: "در حال تغییر…",
  },
  fil: {
    title: "👑 Mag-upgrade sa VIP",
    subtitle: "I-unlock ang private rooms kasama ang mga kaibigan at zero ads!",
    privilege1Title: "Private rooms",
    privilege1Desc: "Private rooms para sa 2–4 manlalaro",
    privilege2Title: "Walang ads",
    privilege2Desc: "Walang ads habambuhay sa classic at challenge",
    privilege3Title: "Eksklusibong karangalan",
    privilege3Desc: "Gintong badge sa leaderboard at profile",
    privilege4Title: "Prayoridad",
    privilege4Desc: "Unang lumalabas ang mga quiz mo",
    promoBadge: "Espesyal na alok",
    planATitle: "Plan A · Sikat",
    planABadge: "Limitadong oras",
    planAPrice: "NT$ 19 / buwan",
    planBTitle: "Plan B",
    planBPrice: "NT$ 39",
    planBDesc: "Lifetime na bili (permanenteng walang ads at lahat ng feature)",
    payBtn: "💳 Magpatuloy sa bayad",
    closeBtn: "Mamaya na, nakuha ko",
    testToggle: "🛠️ Local test: i-toggle ang VIP",
    testBusy: "Lumilipat…",
  },
  da: {
    title: "👑 Opgrader til VIP",
    subtitle: "Lås vennerum op og nyd siden helt uden reklamer!",
    privilege1Title: "Private rum",
    privilege1Desc: "Private rum til 2–4 spillere",
    privilege2Title: "Uden reklamer",
    privilege2Desc: "Ingen reklamer for evigt i klassisk og udfordring",
    privilege3Title: "Eksklusiv ære",
    privilege3Desc: "Guldmærke på ranglisten og profilen",
    privilege4Title: "Prioritet",
    privilege4Desc: "Dine spørgsmål vises først",
    promoBadge: "Særtilbud",
    planATitle: "Plan A · Populær",
    planABadge: "Begrænset tid",
    planAPrice: "NT$ 19 / md",
    planBTitle: "Plan B",
    planBPrice: "NT$ 39",
    planBDesc: "Livstidskøb (permanent reklamefrit og alle funktioner)",
    payBtn: "💳 Gå til betaling",
    closeBtn: "Senere, forstået",
    testToggle: "🛠️ Lokal test: skift VIP",
    testBusy: "Skifter…",
  },
  fi: {
    title: "👑 Päivitä VIPiksi",
    subtitle: "Avaa kaverihuoneet ja nauti sivustosta ilman mainoksia!",
    privilege1Title: "Yksityishuoneet",
    privilege1Desc: "Yksityishuoneet 2–4 pelaajalle",
    privilege2Title: "Ilman mainoksia",
    privilege2Desc: "Ei mainoksia pysyvästi klassikossa eikä haasteessa",
    privilege3Title: "Ainutlaatuinen kunnia",
    privilege3Desc: "Kultainen merkki tulostaululla ja profiilissa",
    privilege4Title: "Etusija",
    privilege4Desc: "Kysymyksesi näytetään ensin",
    promoBadge: "Erikoistarjous",
    planATitle: "Paketti A · Suosittu",
    planABadge: "Rajoitettu aika",
    planAPrice: "NT$ 19 / kk",
    planBTitle: "Paketti B",
    planBPrice: "NT$ 39",
    planBDesc: "Elinikäinen osto (pysyvästi mainokseton ja kaikki ominaisuudet)",
    payBtn: "💳 Siirry maksamaan",
    closeBtn: "Myöhemmin, selvä",
    testToggle: "🛠️ Paikallinen testi: vaihda VIP",
    testBusy: "Vaihdetaan…",
  },
};

export function vipCopyFor(language: LanguageCode): VipModalCopy {
  return VIP_COPY[language] ?? VIP_COPY.en;
}
